Repository osquery/osquery, pull requests merged in 2018-05, with the labels that each got.

#4312 fbthrift: Second set of Apache and FbThrift refactors
  include/osquery/extensions.h
  osquery/extensions/extensions.cpp
  osquery/extensions/impl_fbthrift.cpp
  osquery/extensions/impl_thrift.cpp
  osquery/extensions/interface.cpp
  osquery/extensions/interface.h
  osquery/extensions/tests/extensions_tests.cpp
Labels: cla signed

#4341 Fix registry locking for plugin method
  include/osquery/registry.h
Labels: bug, cla signed

#4343 Fix init when using fbthrift (and folly)
  osquery/core/init.cpp
Labels: bug, cla signed

#4255 Updating reverse shell query in osx-attacks
  packs/osx-attacks.conf
Labels: cla signed, packs

#4321 Fix parsing of EventData block for Windows Events.
  osquery/tables/events/windows/windows_events.cpp
Labels: Windows, bug, cla signed, events

#4347 Move singleton accessors into implementations
  include/osquery/config.h
  include/osquery/posix/system.h
  include/osquery/registry.h
  osquery/config/config.cpp
  osquery/core/system.cpp
  osquery/registry/registry.cpp
Labels: bug, cla signed

#4346 style: fixing WEL parsing ternary
  osquery/tables/events/windows/windows_events.cpp
Labels: Windows, cla signed, events

#4349 sync: Fix sync to handle new fbthrift refactor
  osquery/extensions/impl_fbthrift.cpp
  osquery/logger/logger.cpp
  tools/codegen/gentargets.py
  tools/sync.sh
Labels: bug, build/test, cla signed

#4332 Update unwanted-chrome-extensions.conf
  packs/unwanted-chrome-extensions.conf
Labels: cla signed, packs

#4352 Remove clang pragmas from tables.h
  include/osquery/tables.h
Labels: Windows, build/test, cla signed

#4350 Separate general hashing methods from table implementation
  osquery/CMakeLists.txt
  osquery/carver/carver.cpp
  osquery/carver/tests/carver_tests.cpp
  osquery/core/hashing.cpp
  osquery/core/hashing.h
  osquery/sql/sqlite_hashing.cpp
  osquery/tables/events/event_utils.cpp
  osquery/tables/sleuthkit/sleuthkit.cpp
  osquery/tables/system/darwin/acpi_tables.cpp
  osquery/tables/system/darwin/keychain_utils.cpp
  osquery/tables/system/hash.cpp
  osquery/tables/system/linux/acpi_tables.cpp
  osquery/tables/system/posix/smbios_utils.cpp
Labels: bug, build/test, cla signed, virtual tables

#4345 Make options parser ignore invalid options
  osquery/config/parsers/options.cpp
Labels: bug, cla signed

#4267 tools/get_platform.py: add support for nixos
  tools/get_platform.py
Labels: Linux, build/test, cla signed

#4355 Code audit for flags and dispatcher parts
  include/osquery/dispatcher.h
  include/osquery/flags.h
  osquery/carver/carver.h
  osquery/config/config.cpp
  osquery/core/flags.cpp
  osquery/core/watcher.h
  osquery/dispatcher/dispatcher.cpp
  osquery/dispatcher/distributed.h
Labels: bug, cla signed

#4316 service: add full path for service binary
  osquery/main/main.cpp
  osquery/main/main.h
  osquery/main/posix/main.cpp
  osquery/main/windows/main.cpp
Labels: Windows, cla signed, deployment

#4313 Add an mdfind table to macOS
  osquery/tables/system/darwin/mdfind.mm
  osquery/tables/system/darwin/tests/mdfind_tests.cpp
  specs/darwin/mdfind.table
Labels: cla signed, feature, macOS, virtual tables

#4278 New Tables: Cups Jobs and Cups Destinations
  osquery/tables/system/darwin/cups_destinations.cpp
  osquery/tables/system/darwin/cups_jobs.cpp
  specs/darwin/cups_destinations.table
  specs/darwin/cups_jobs.table
Labels: cla signed, feature, macOS, ready for review, virtual tables

#4361 Remove --logger_min_stderr from service files
  tools/deployment/com.facebook.osqueryd.plist
  tools/deployment/osqueryd.initd
  tools/deployment/osqueryd.service
Labels: RFC, cla signed, configuration, deployment, logging

#4263 Add namespaces to processes table on linux
  osquery/tables/system/linux/processes.cpp
  specs/processes.table
Labels: Linux, cla signed, feature

#4303 recover interface flags
  osquery/tables/networking/posix/interfaces.cpp
Labels: Linux, cla signed, virtual tables

#4215 tables: updating confusing info messages for interface details table
  osquery/tables/networking/windows/interfaces.cpp
Labels: Jenkins error, Windows, cla signed, user experience, virtual tables

#4363 Fix USB class/subclass IDs on darwin
  osquery/tables/system/darwin/usb_devices.cpp
Labels: bug, cla signed, macOS

#4365 Format code in usb_devices
  osquery/tables/system/darwin/usb_devices.cpp
Labels: build/test, cla signed

#4366 release: adding Windows links to release script
  tools/release/new_release.sh
Labels: Windows, cla signed, website

#4271 New ATC Tables
  include/osquery/system.h
  osquery/carver/tests/carver_tests.cpp
  osquery/config/CMakeLists.txt
  osquery/config/additional_parsers/auto_constructed_tables.cpp
  osquery/config/additional_parsers/auto_constructed_tables.h
  osquery/config/config.cpp
  osquery/config/packs.cpp
  osquery/core/system.cpp
  osquery/sql/CMakeLists.txt
  osquery/sql/sqlite_util.h
  osquery/sql/virtual_sqlite_table.cpp
  osquery/tables/yara/yara_utils.cpp
  tools/tests/test.config
  tools/tests/test.config.d/extra_options.conf
  tools/tests/test.config.d/osquery.conf
  tools/tests/test_atc_db.db
  tools/tests/test_base.py
  tools/tests/test_http_server.py
  tools/tests/test_osqueryi.py
Labels: RFC, cla signed, feature, ready for review, virtual tables

#4328 [darwin] Fix a variety of small bugs in system_controls
  osquery/tables/system/darwin/sysctl_utils.cpp
Labels: bug, cla signed, macOS

#4369 Correct process uid for user name mapping and added is_elevated_token column
  osquery/tables/system/windows/processes.cpp
  specs/processes.table
Labels: Windows, bug, cla signed, virtual tables

#4351 tables: adds a Powershell events table to Windows
  osquery/config/parsers/feature_vectors.cpp
  osquery/config/parsers/feature_vectors.h
  osquery/tables/events/windows/powershell_events.cpp
  specs/windows/powershell_events.table
  tools/deployment/osquery.example.conf
Labels: Windows, cla signed, events, ready for review, virtual tables

#4367 Pass name of query to lambda in Config::scheduledQueries by value
  include/osquery/config.h
  osquery/config/config.cpp
  osquery/config/tests/config_tests.cpp
  osquery/config/tests/packs_tests.cpp
  osquery/dispatcher/scheduler.cpp
  osquery/events/events.cpp
  osquery/tables/utility/osquery.cpp
Labels: cla signed

#4376 Add manufaturer and service to interface_details table for Windows
  osquery/tables/networking/windows/interfaces.cpp
  specs/interface_details.table
Labels: Windows, cla signed, virtual tables

#4377 packs: Adding ColdRoot RAT to osx-attacks detection list
  packs/osx-attacks.conf
Labels: cla signed, macOS, packs

#4315 NPM Packages Table on Linux
  osquery/tables/system/linux/npm_packages.cpp
  specs/linux/npm_packages.table
Labels: Linux, cla signed, virtual tables

#4383 Add const qualifier to some Config methods
  include/osquery/config.h
  osquery/config/config.cpp
Labels: cla signed, configuration, hardening

#4374 Handle placeholder hardware UUIDs
  include/osquery/system.h
  osquery/core/system.cpp
  osquery/core/tests/system_test.cpp
Labels: cla signed, do not merge, feature

#4386 bug: do not wait for main service thread before reporting stop to SCM
  osquery/core/init.cpp
  osquery/core/posix/process_ops.cpp
  osquery/core/process.h
  osquery/core/windows/process_ops.cpp
  osquery/main/windows/main.cpp
  tools/tests/test_windows_service.py
Labels: Windows, bug, cla signed, daemon

#4337 Refactor tables to bail out early on error. Add encryption method to bitlocker_info.
  osquery/tables/system/windows/bitlocker_info.cpp
  osquery/tables/system/windows/disk_info.cpp
  specs/windows/bitlocker_info.table
Labels: Windows, cla signed, virtual tables

#4269 Plumb used columns into QueryContext; use that to make processes table more efficient on macOS
  include/osquery/sql.h
  include/osquery/tables.h
  osquery/core/tables.cpp
  osquery/core/watcher.cpp
  osquery/dispatcher/scheduler.cpp
  osquery/sql/sql.cpp
  osquery/sql/sqlite_util.cpp
  osquery/sql/virtual_table.cpp
  osquery/tables/system/darwin/processes.cpp
Labels: API change, cla signed, performance, virtual tables

#4370 llvm 6.0 and libFuzzer implementation
  CMakeLists.txt
  Makefile
  docs/wiki/development/building.md
  osquery/CMakeLists.txt
  osquery/filesystem/linux/proc.cpp
  osquery/main/fuzz.cpp
  osquery/remote/uri.cpp
  tools/provision/formula/Abstract/abstract-osquery-formula.rb
  tools/provision/formula/libcpp.rb
  tools/provision/formula/llvm.rb
Labels: build/test, cla signed, dynamic analysis

#4373 removed startup_items from linux platform.
  osquery/tables/system/linux/users.cpp
  specs/macwin/startup_items.table
Labels: bug, cla signed

#4217 tables: adding user_groups table for Windows
  osquery/core/windows/process_ops.cpp
  osquery/core/windows/process_ops.h
  osquery/tables/system/windows/groups.cpp
  osquery/tables/system/windows/user_groups.cpp
  specs/user_groups.table
Labels: Windows, cla signed, ready for review, virtual tables

#4253 mac: add 'state' to process_open_sockets
  osquery/filesystem/linux/proc.h
  osquery/tables/system/darwin/process_open_descriptors.cpp
  specs/process_open_sockets.table
Labels: cla signed, feature, macOS

#4390 Fixing OSQUERY_DEPS in building documentation
  docs/wiki/development/building.md
Labels: cla signed

#4247 Add documentation for Darwin ALF "Block all incoming connections" mode
  specs/darwin/alf.table
Labels: cla signed, documentation, virtual tables

#4389 update building documentation to reference Windows
  docs/wiki/development/building.md
Labels: Windows, cla signed, documentation

#4394 Adding MacSearch adware to osx-attacks
  packs/osx-attacks.conf
Labels: cla signed

#4118 bios_info table for Windows.
  osquery/tables/system/windows/wmi_bios_info.cpp
  specs/windows/wmi_bios_info.table
Labels: Windows, cla signed, needs response, virtual tables

#4138 tables: Virtual table implemention for memory devices from SMBIOS
  osquery/tables/system/darwin/smbios_tables.cpp
  osquery/tables/system/linux/smbios_tables.cpp
  osquery/tables/system/linux/smbios_utils.h
  osquery/tables/system/posix/smbios_utils.cpp
  osquery/tables/system/smbios_utils.h
  specs/blacklist
  specs/posix/memory_devices.table
Labels: Linux, cla signed, virtual tables

#4320 virtual_tables: add link_speed column to interface_details for linux
  osquery/tables/networking/posix/interfaces.cpp
  specs/interface_details.table
Labels: Linux, cla signed, virtual tables

#4397 aws: Deal with missing uuid file on C5/M5 instances.
  osquery/utils/aws_util.cpp
Labels: AWS, cla signed

#4399 http_client: Always close socket on exception
  osquery/remote/http/http_client.cpp
  osquery/remote/transports/tls.cpp
Labels: bug, cla signed, remote

#4400 packs: Fix blacklist option bool assumption
  osquery/config/packs.cpp
Labels: bug, cla signed, configuration

#4387 Apply const qualifier for Config::packs(...) method
  include/osquery/config.h
  osquery/config/config.cpp
  osquery/config/tests/config_tests.cpp
  osquery/config/tests/packs_tests.cpp
  osquery/devtools/shell.cpp
  osquery/tables/utility/osquery.cpp
Labels: cla signed, configuration, hardening, needs response

#4401 Fix debuginfo build-id subdirectory
  tools/deployment/make_linux_package.sh
Labels: Linux, bug, cla signed, packaging

#4405 [osx] added autorelease pools
  osquery/tables/networking/darwin/wifi.mm
  osquery/tables/networking/darwin/wifi_status.mm
  osquery/tables/networking/darwin/wifi_survey.mm
  osquery/tables/system/darwin/account_policy_data.mm
  osquery/tables/system/darwin/apps.mm
  osquery/tables/system/darwin/authorizations.mm
  osquery/tables/system/darwin/certificates.mm
  osquery/tables/system/darwin/disk_encryption.mm
  osquery/tables/system/darwin/event_taps.mm
  osquery/tables/system/darwin/mdfind.mm
  osquery/tables/system/darwin/packages.mm
  osquery/tables/system/darwin/shared_folders.mm
  osquery/tables/system/darwin/signature.mm
  osquery/tables/system/darwin/user_groups.mm
Labels: cla signed

#4404 Fixed over release of object on osx
  osquery/tables/system/darwin/disk_encryption.mm
Labels: bug, cla signed, macOS

#4406 Fixing memory leak in mdfind table
  osquery/tables/system/darwin/mdfind.mm
Labels: cla signed, macOS, memory leak

#4412 Remove useless links on debug package creation
  tools/deployment/make_linux_package.sh
Labels: bug, cla signed

#4413 Make tags targets PHONY
  Makefile
Labels: bug, cla signed

#4265 Added custom path functions
  osquery/sql/CMakeLists.txt
  osquery/sql/sqlite_encoding.cpp
  osquery/sql/sqlite_filesystem.cpp
  osquery/sql/sqlite_hashing.cpp
  osquery/sql/sqlite_math.cpp
  osquery/sql/sqlite_operations.cpp
  osquery/sql/sqlite_string.cpp
  osquery/sql/sqlite_util.cpp
  osquery/sql/sqlite_util.h
Labels: SQL, cla signed, feature, needs response

#4407 Fixed Python packages table
  osquery/tables/system/linux/smbios_utils.h
  osquery/tables/system/python_packages.cpp
  specs/python_packages.table
Labels: bug, cla signed

#4426 Fix files with no new line at eof
  osquery/config/additional_parsers/auto_constructed_tables.h
  osquery/events/linux/auditeventpublisher.h
  osquery/remote/uri.h
  tools/codegen/amalgamate.py
Labels: cla signed

#4419 Adding readonly_rootfs field to docker_containers table.
  osquery/tables/applications/posix/docker.cpp
  specs/posix/docker_containers.table
Labels: cla signed, docker, virtual tables

#4409 tables: memory related SMBIOS tables
  osquery/tables/system/darwin/smbios_tables.cpp
  osquery/tables/system/linux/smbios_tables.cpp
  osquery/tables/system/posix/smbios_utils.cpp
  osquery/tables/system/smbios_utils.h
  specs/blacklist
  specs/posix/memory_array_mapped_addresses.table
  specs/posix/memory_arrays.table
  specs/posix/memory_device_mapped_addresses.table
  specs/posix/memory_error_info.table
Labels: cla signed, feature

#4430 Remove unused member from SchedulerRunner class
  osquery/dispatcher/scheduler.h
Labels: cla signed, hardening, refactor

#4435 deps: Allow GCC 7 to build glibc-legacy 2.13
  tools/provision/formula/glibc-legacy.rb
Labels: Linux, cla signed, dependencies

#4436 deps: Simplify LLVM includes
  tools/provision/formula/Abstract/abstract-osquery-formula.rb
  tools/provision/formula/libcpp.rb
  tools/provision/formula/llvm.rb
Labels: Linux, cla signed, dependencies

#4437 deps: Update aws-sdk-cpp to version 1.4.55
  osquery/utils/tests/aws_util_tests.cpp
  tools/provision/formula/aws-sdk-cpp.rb
Labels: Linux, bug, cla signed, dependencies, macOS

#4439 deps: Update libdpkg to version 1.19.0.5
  tools/provision/formula/libdpkg.rb
Labels: Linux, cla signed, dependencies

#4440 deps: Update sleuthkit to version 4.6.1
  tools/provision/formula/sleuthkit.rb
Labels: Linux, cla signed, dependencies, macOS

#4441 deps: Patch RapidJSON to remove march native
  tools/provision/formula/rapidjson.rb
Labels: Linux, cla signed, dependencies, macOS

#4444 split registry to separate classes
  include/osquery/plugin.h
  include/osquery/registry.h
  include/osquery/registry_factory.h
  include/osquery/registry_interface.h
  osquery/registry/CMakeLists.txt
  osquery/registry/plugin.cpp
  osquery/registry/registry_factory.cpp
  osquery/registry/registry_interface.cpp
Labels: cla signed

#4434 Logger config
  osquery/config/config.cpp
  osquery/config/parsers/logger.cpp
  osquery/config/parsers/logger.h
Labels: cla signed, feature

#4425 cpu_type fixed for linux
  osquery/tables/system/linux/system_info.cpp
Labels: API change, cla signed, feature

#4393 Simple solution to reduce drift time in loop of scheduled queries
  osquery/dispatcher/scheduler.cpp
  osquery/dispatcher/scheduler.h
  osquery/dispatcher/tests/scheduler_tests.cpp
Labels: bug, cla signed, daemon

#4443 reworked core cmakefiles.txt
  CMake/CMakeLibs.cmake
  CMakeLists.txt
  osquery/core/CMakeLists.txt
Labels: build/test, cla signed

#4446 reorganized includes to improve compile time 2
  include/osquery/config.h
  include/osquery/database.h
  include/osquery/dispatcher.h
  include/osquery/filesystem.h
  include/osquery/flags.h
  include/osquery/query.h
  include/osquery/registry_interface.h
  include/osquery/system.h
  include/osquery/tables.h
  osquery/carver/carver.h
  osquery/core/hashing.cpp
  osquery/core/posix/utils.cpp
  osquery/core/utils.h
  osquery/dispatcher/tests/dispatcher_tests.cpp
  osquery/tables/system/darwin/keychain_utils.cpp
  osquery/tables/system/linux/kernel_integrity.cpp
  osquery/tables/system/windows/processes.cpp
Labels: cla signed

#4396 osquery::Error && osquery::Expected
  include/osquery/error.h
  include/osquery/expected.h
  include/osquery/status.h
  osquery/core/tests/error_tests.cpp
  osquery/core/tests/exptected_tests.cpp
Labels: cla signed
