Repository osquery/osquery, pull requests merged in 2018-08, with the labels that each got.

#4697 Debug only wrapper class and functions to perform some verifications
  osquery/CMakeLists.txt
  osquery/debug/CMakeLists.txt
  osquery/debug/debug_only.h
  osquery/debug/tests/debug_only_tests.cpp
Labels: cla signed, debt, feature, ready for review

#4784 Add ppid and cwd field for each new created process
  osquery/tables/events/linux/process_events.cpp
Labels: cla signed, process auditing

#4791 Killswitch TLS plugin improved interface
  osquery/killswitch/plugins/killswitch_tls.cpp
Labels: cla signed

#4789 added base class for new db implementation
  osquery/core/CMakeLists.txt
  osquery/core/database/database.cpp
  osquery/core/database/database.h
Labels: cla signed

#4796 pauseMili to pause transform
  include/osquery/config.h
  include/osquery/dispatcher.h
  osquery/config/config.cpp
  osquery/config/tests/config_tests.cpp
  osquery/core/watcher.cpp
  osquery/dispatcher/dispatcher.cpp
  osquery/dispatcher/distributed_runner.cpp
  osquery/dispatcher/scheduler.cpp
  osquery/dispatcher/tests/dispatcher_tests.cpp
  osquery/events/events.cpp
  osquery/events/kernel.cpp
  osquery/events/linux/udev.cpp
  osquery/events/windows/windows_event_log.cpp
  osquery/extensions/extensions.cpp
  osquery/killswitch/killswitch_refreshable_plugin.cpp
  osquery/logger/plugins/aws_log_forwarder.h
  osquery/logger/plugins/buffered.cpp
  osquery/logger/plugins/kafka_producer.cpp
  osquery/numeric_monitoring/numeric_monitoring.cpp
Labels: cla signed, debt

#4793 Move out base64 decode/encode functions to separate file
  osquery/carver/carver.cpp
  osquery/core/CMakeLists.txt
  osquery/core/base64.cpp
  osquery/core/base64.h
  osquery/core/conversions.cpp
  osquery/core/conversions.h
  osquery/core/tests/base64_tests.cpp
  osquery/core/tests/conversions_tests.cpp
  osquery/filesystem/darwin/plist.mm
  osquery/filesystem/darwin/tests/plist_tests.cpp
  osquery/sql/sqlite_encoding.cpp
  osquery/tables/system/darwin/extended_attributes.cpp
  osquery/tables/system/darwin/tests/certificates_tests.cpp
  osquery/tables/system/darwin/time_machine.cpp
Labels: cla signed, debt, refactor

#4792 Clarify licensing
  CONTRIBUTING.md
  LICENSE
  LICENSE-Apache-2.0
  LICENSE-GPL-2.0
Labels: cla signed, documentation

#4714 Audit fixes
  osquery/events/events.cpp
  osquery/events/tests/events_database_tests.cpp
Labels: Linux, bug, cla signed, events, ready for review

#4790 Add debug checks for wrong access of error in Expected
  include/osquery/expected.h
  osquery/core/tests/exptected_tests.cpp
Labels: cla signed, feature, ready for review, refactor

#4705 Avoid warnings about implicit conversion from wchar_t -> char
  osquery/tables/networking/windows/interfaces.cpp
  osquery/tables/system/windows/drivers.cpp
Labels: Windows, bug, cla signed

#4800 Use putBatch only for multiple puts, fix bug in setDatabaseVal
  osquery/database/database.cpp
  osquery/database/tests/database_tests.cpp
Labels: bug, cla signed

#4804 remove io_service
  osquery/dispatcher/CMakeLists.txt
  osquery/dispatcher/io_service.cpp
  osquery/dispatcher/io_service.h
  osquery/logger/plugins/tests/kafka_producer_tests.cpp
  osquery/main/main.cpp
  osquery/remote/transports/tls.cpp
Labels: RFC, cla signed, debt, ready for review

#4781 deps: boost updates for windows vs 2017
  CMakeLists.txt
  tools/provision.ps1
  tools/provision/chocolatey/boost-msvc14.ps1
Labels: Windows, build/test, cla signed, dependencies

#4704 Introduce .types shell command
  osquery/devtools/shell.cpp
Labels: cla signed, feature, shell

#4778 Fix up `stringFromCFString` bug related to non ascii strings
  osquery/core/darwin/conversions.cpp
  osquery/core/tests/conversions_tests.cpp
Labels: bug, cla signed, macOS, ready for review

#4805 remove resolvedpath class
  osquery/events/pathset.h
Labels: cla signed, dead code, debt, ready for review

#4829 Split issue template into multiple types
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Blueprint.md
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Question.md
Labels: cla signed, documentation

#4830 Create Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla signed, documentation

#4798 Improve contribution guidelines
  CONTRIBUTING.md
Labels: cla signed, documentation

#4835 Improve SUPPORT.md
  SUPPORT.md
Labels: cla signed, documentation

#4834 Cleanup old text from README
  README.md
Labels: cla signed, documentation

#4838 Fix make sync
  osquery/database/CMakeLists.txt
  osquery/logger/CMakeLists.txt
  osquery/sql/CMakeLists.txt
Labels: bug, cla signed, cmake

#4842 spelling errors
  osquery/core/database/database.h
Labels: cla signed

#4841 missing new line
  osquery/core/windows/ntapi.h
Labels: cla signed

#4840 support different version of the rapid json
  tools/codegen/gentargets.py
Labels: cla signed

#4846 linter warnings
  include/osquery/killswitch.h
  osquery/core/database/database.h
  osquery/core/tables.cpp
  osquery/killswitch/killswitch.cpp
  osquery/killswitch/killswitch_refreshable_plugin.cpp
Labels: cla signed

#4845 tables: dmiString function param to use string index
  osquery/tables/system/linux/smbios_tables.cpp
  osquery/tables/system/linux/system_info.cpp
  osquery/tables/system/posix/smbios_utils.cpp
  osquery/tables/system/smbios_utils.h
Labels: cla signed

#4847 get rid of std::regex
  osquery/database/database.cpp
Labels: cla signed

#4807 Add constness for the methods of class `WmiRequest`
  osquery/core/system.cpp
  osquery/core/windows/wmi.h
  osquery/tables/networking/windows/arp_cache.cpp
  osquery/tables/networking/windows/interfaces.cpp
  osquery/tables/system/windows/bitlocker_info.cpp
  osquery/tables/system/windows/cpu_info.cpp
  osquery/tables/system/windows/disk_info.cpp
  osquery/tables/system/windows/drivers.cpp
  osquery/tables/system/windows/logical_drives.cpp
  osquery/tables/system/windows/os_version.cpp
  osquery/tables/system/windows/patches.cpp
  osquery/tables/system/windows/physical_disk_performance.cpp
  osquery/tables/system/windows/processes.cpp
  osquery/tables/system/windows/shared_resources.cpp
  osquery/tables/system/windows/smbios_tables.cpp
  osquery/tables/system/windows/system_info.cpp
  osquery/tables/system/windows/video_info.cpp
  osquery/tables/system/windows/wmi_bios_info.cpp
  osquery/tables/system/windows/wmi_cli_event_consumers.cpp
  osquery/tables/system/windows/wmi_event_filters.cpp
  osquery/tables/system/windows/wmi_filter_consumer_binding.cpp
  osquery/tables/system/windows/wmi_script_event_consumers.cpp
Labels: Windows, cla signed, hardening

#4831 resolve -Wwritable-strings warning
  osquery/devtools/shell.cpp
Labels: cla signed, ready for review

#4797 added in memory db
  osquery/core/CMakeLists.txt
  osquery/core/database/in_memory_database.cpp
  osquery/core/database/in_memory_database.h
  osquery/core/database/tests/in_memory_database_tests.cpp
Labels: cla signed

#4768 Remove `safeStrtol` from conversion.h (use `tryTo<long>` instead)
  osquery/config/packs.cpp
  osquery/core/conversions.h
  osquery/core/darwin/iokit.hpp
  osquery/core/flags.cpp
  osquery/core/system.cpp
  osquery/tables/events/linux/socket_events.cpp
  osquery/tables/networking/windows/arp_cache.cpp
  osquery/tables/sleuthkit/sleuthkit.cpp
  osquery/tables/system/linux/md_tables.cpp
  osquery/tables/system/linux/memory_info.cpp
  osquery/tables/system/linux/user_groups.cpp
  osquery/tables/system/linux/users.cpp
  osquery/tables/system/windows/os_version.cpp
Labels: cla signed, debt, easy, ready for review, refactor

#4851 deps: Add bottle hashes for ssdeep-cpp
  tools/provision/formula/ssdeep-cpp.rb
Labels: cla signed, dependencies

#4761 Improve extensions documentation
  docs/wiki/deployment/extensions.md
  docs/wiki/development/osquery-sdk.md
Labels: cla signed, documentation, extensions

#4857 clang flexible-array-extensions warnings fix
  osquery/tables/system/darwin/packages.h
Labels: cla signed

#4856 A missing Gatekeeper prefs file indicates it is on
  osquery/tables/system/darwin/gatekeeper.cpp
Labels: bug, cla signed, macOS

#4899 docs: fix the definition of 'posix' for the platform key
  docs/wiki/deployment/configuration.md
Labels: cla signed

#4901 Add task issue template
  .github/ISSUE_TEMPLATE/Free_Form.md
Labels: cla signed, documentation

#4906 fixed move assignment operator for expected
  include/osquery/expected.h
Labels: bug, cla signed

#4911 fix set thread warnings
  osquery/core/system.cpp
Labels: cla signed, hardening

#4913 posix treat warnings as errors
  CMakeLists.txt
Labels: cla signed

#4900 Add hopcount entry to the 'routes' table
  osquery/tables/networking/darwin/routes.cpp
  osquery/tables/networking/freebsd/routes.cpp
  osquery/tables/networking/linux/routes.cpp
  specs/routes.table
Labels: cla signed

#4848 tables: fix cpu_physical_cores and cpu_logical_cores on linux
  osquery/tables/system/linux/system_info.cpp
  specs/system_info.table
Labels: Linux, bug, cla signed, needs response

#4852 libfuzz: Add SMBIOS table fuzzing
  osquery/main/fuzz.cpp
Labels: cla signed, dynamic analysis, hardening, virtual tables

#4968 Update linux installation guide
  docs/wiki/installation/install-linux.md
Labels: cla signed, documentation

#4934 route table: properly display the default IPv6 route on Linux
  osquery/tables/networking/linux/routes.cpp
Labels: API change, cla signed, ready for review

#4391 pci_devices: model and vendor information from system PCI db && add subsystem info
  osquery/tables/system/linux/pci_devices.cpp
  osquery/tables/system/linux/pci_devices.h
  osquery/tables/system/linux/tests/pci_devices_test.cpp
  specs/posix/pci_devices.table
Labels: Linux, cla signed, needs response, virtual tables

#4975 Reorder hashes in the ssdeep-cpp formula
  tools/provision/formula/ssdeep-cpp.rb
Labels: bug, cla signed, dependencies, macOS

#5070 Remove boost SHA1 UUID dependency
  osquery/config/config.cpp
  osquery/config/packs.cpp
  osquery/config/tests/config_tests.cpp
  osquery/core/conversions.cpp
  osquery/core/conversions.h
  osquery/core/tests/conversions_tests.cpp
Labels: bug, cla signed, configuration

#4912 rocksdb implementation part
  osquery/CMakeLists.txt
  osquery/core/CMakeLists.txt
  osquery/core/database/database.h
  osquery/core/database/in_memory_database.cpp
  osquery/core/database/in_memory_database.h
  osquery/core/database/rocksdb_database.cpp
  osquery/core/database/rocksdb_database.h
  osquery/core/database/tests/in_memory_database_tests.cpp
  osquery/core/database/tests/rocksdb_database_tests.cpp
  osquery/database/plugins/rocksdb.cpp
  osquery/database/plugins/rocksdb.h
  osquery/filesystem/CMakeLists.txt
Labels: cla signed, database, in progress

#4972 get rid of alias verbose_debug and debug
  osquery/config/parsers/options.cpp
  osquery/logger/logger.cpp
Labels: API change, cla signed

#4981 route table: get the value of the MTU on Linux
  osquery/tables/networking/linux/routes.cpp
Labels: cla signed

#5066 Correct --enable_extensions_watchdog description
  osquery/core/watcher.cpp
Labels: bug, cla signed

#4978 Match how logger_min_stderr works to doc
  osquery/logger/logger.cpp
  osquery/logger/tests/logger_tests.cpp
Labels: API change, cla signed

#4971 default logtostderr to true (remove logStderrOnly)
  osquery/logger/logger.cpp
Labels: API change, cla signed

#4969 remove primary logger concept
  docs/wiki/installation/cli-flags.md
  osquery/logger/logger.cpp
  osquery/logger/tests/logger_tests.cpp
Labels: API change, cla signed, debt

#4970 get rid of aliased flag log_result_events
  docs/wiki/deployment/logging.md
  osquery/logger/logger.cpp
Labels: API change, cla signed

#5076 Log when an extension is registered or dies
  osquery/extensions/interface.cpp
Labels: cla signed, hardening

#5080 remove unused force_permissions
  include/osquery/filesystem.h
  osquery/filesystem/filesystem.cpp
  osquery/filesystem/tests/filesystem_tests.cpp
  osquery/logger/plugins/filesystem_logger.cpp
  osquery/remote/enroll/tests/enroll_tests.cpp
Labels: cla signed

#5083 unused code logger
  osquery/logger/logger.cpp
Labels: cla signed

#5089 cleanup after the primary logger concept removal
  osquery/logger/logger.cpp
Labels: cla signed

#5088 Make error messages in Expected check different to distinguish problems
  include/osquery/expected.h
  osquery/core/tests/exptected_tests.cpp
Labels: feature

#5085 Fix up usage of debug_only::Var in expected assign operator
  include/osquery/expected.h
Labels: bug, cla signed

#5073 deps: Update Vagrant macOS target to 10.13
  Vagrantfile
  tools/provision/darwin.sh
  tools/release/build_release.sh
  tools/release/deps_release.sh
Labels: build/test, cla signed, dependencies, macOS

#4849 SMBIOS `oem_strings` table
  osquery/tables/system/darwin/smbios_tables.cpp
  osquery/tables/system/linux/smbios_tables.cpp
  osquery/tables/system/posix/smbios_utils.cpp
  osquery/tables/system/smbios_utils.h
  specs/blacklist
  specs/posix/oem_strings.table
Labels: cla signed, feature, virtual tables

#5108 added uptime sanity check
  osquery/tests/integration/tables/CMakeLists.txt
  osquery/tests/integration/tables/uptime.cpp
Labels: cla signed

#5100 put config backup feature behind killswitch
  include/osquery/killswitch.h
  osquery/config/config.cpp
  osquery/killswitch/killswitch.cpp
Labels: cla signed

#5077 rearrange initLogger disable capabilities
  osquery/core/init.cpp
  osquery/logger/logger.cpp
Labels: cla signed, ready for review

#5095 Fix of issue #4674: Updated Documentation
  tools/tests/test_http_server.py
Labels: cla signed

#5087 Add an rvalue constructor for Expected
  include/osquery/expected.h
Labels: bug, cla signed

#5097 Implement setThreadName() for FreeBSD
  osquery/core/system.cpp
Labels: cla signed

#5082 Expand "opaque" values in system_controls table
  osquery/tables/system/darwin/sysctl_utils.cpp
  specs/posix/system_controls.table
Labels: cla signed

#4833 Helper functions `tryTake`, `tryTakeCopy` to lookup in key-value tables
  osquery/core/CMakeLists.txt
  osquery/core/map_take.h
  osquery/core/tests/map_take_tests.cpp
  osquery/devtools/printer.cpp
Labels: cla signed, feature, ready for review

#4980 RAII based scope guard class
  osquery/core/CMakeLists.txt
  osquery/core/scope_guard.h
  osquery/core/tests/scope_guard_tests.cpp
Labels: cla signed, feature, ready for review

#5098 socket_events: Use local_port/local_address for bind()
  osquery/tables/events/linux/socket_events.cpp
Labels: bug, cla signed, events

#5092 Run `make test_debug` in order to run the tests for debug build
  tools/lib.sh
Labels: build/test, cla signed

#5122 [Table sanity check] hash
  osquery/tests/integration/tables/hash.cpp
Labels: cla signed, test

#5119 [Table sanity check] system info
  osquery/tests/integration/tables/helper.cpp
  osquery/tests/integration/tables/system_info.cpp
Labels: cla signed, test

#5121 [Table sanity check] Integration test for the linux kernel modules table
  osquery/tests/integration/tables/kernel_modules.cpp
Labels: Linux, cla signed, kernel, test

#5120 [Table sanity check] Integration tests for deb_packages
  osquery/tests/integration/tables/deb_packages.cpp
Labels: Linux, cla signed, test

#5129 Use just std::function for custom validator in table integration tests
  osquery/tests/integration/tables/crontab.cpp
  osquery/tests/integration/tables/helper.cpp
  osquery/tests/integration/tables/helper.h
  osquery/tests/integration/tables/uptime.cpp
Labels: build/test, cla signed, test

#5131 errorbase wdeprecated warning fix
  include/osquery/error.h
Labels: cla signed

#5118 virtual tables: Handle SQLite3 BLOB_TYPE
  osquery/sql/sqlite_encoding.cpp
  osquery/sql/virtual_table.cpp
Labels: SQL, bug, cla signed

#5136 Typo on Ubuntu 17.04 bento box
  Vagrantfile
Labels: bug, cla signed

#5132 [Table sanity check] process_envs
  osquery/tests/integration/tables/process_envs.cpp
Labels: cla signed, test

#5117 Darwin provisioning script to use /usr/local/bin to avoid SIP violation
  tools/provision/darwin.sh
Labels: build/test, cla signed, macOS

#5123 [Table sanity check] time
  osquery/tests/integration/tables/time.cpp
Labels: cla signed, test

#5133 Fix up wrong integer types from validating values from the tables
  osquery/tests/integration/tables/helper.cpp
  osquery/tests/integration/tables/helper.h
Labels: bug, cla signed

#5126 [Table sanity check] file
  osquery/tests/integration/tables/file.cpp
Labels: cla signed, test

#5148 Add quotes for the key and value in assertion messages
  osquery/tests/integration/tables/helper.cpp
Labels: build/test, cla signed

#5151 Fix typo. It's Comma, not Coma :-)
  docs/wiki/installation/cli-flags.md
  osquery/numeric_monitoring/numeric_monitoring.cpp
Labels: cla signed, documentation

#5137 [Table sanity check] sanboxes
  osquery/tests/integration/tables/sandboxes.cpp
Labels: cla signed, test

#5141 [Table sanity check] programs
  osquery/tests/integration/tables/programs.cpp
Labels: cla signed, test

#5146 [Table sanity check] memory_map
  osquery/tests/integration/tables/memory_map.cpp
Labels: cla signed, test

#5142 [Table sanity check] sanity check for the table interface_addresses
  osquery/tables/networking/posix/interfaces.cpp
  osquery/tests/integration/tables/helper.cpp
  osquery/tests/integration/tables/helper.h
  osquery/tests/integration/tables/interface_addresses.cpp
  specs/interface_addresses.table
Labels: build/test, cla signed, test

#5144 [Table sanity check] sanity check for the table logged_in_users
  osquery/tests/integration/tables/logged_in_users.cpp
Labels: build/test, cla signed, test

#5147 [Table sanity check] Integration test for the table system_controls
  osquery/tests/integration/tables/system_controls.cpp
Labels: build/test, cla signed, test

#5149 Make more talkative in terms of unexpected columns
  osquery/tests/integration/tables/helper.cpp
Labels: build/test, cla signed, test

#5143 [Table sanity check] sanity check for the table interface_details
  osquery/tables/networking/posix/interfaces.cpp
  osquery/tables/networking/windows/interfaces.cpp
  osquery/tests/integration/tables/interface_details.cpp
Labels: API change, build/test, test

#5130 [Table sanity check] Integration test for the `known_hosts` table
  osquery/tables/system/posix/known_hosts.cpp
  osquery/tables/system/posix/known_hosts.h
  osquery/tables/system/posix/tests/known_hosts_tests.cpp
  osquery/tests/integration/tables/known_hosts.cpp
Labels: build/test, cla signed, test

#5157 [Table sanity check] Integration test for the 'apt_sources' table
  osquery/tests/integration/tables/apt_sources.cpp
Labels: FreeBSD, Linux, cla signed, table, test

#5145 [Table sanity check] process_open_files
  osquery/tests/integration/tables/process_open_files.cpp
Labels: cla signed, test

#5156 allow numeric_monitoring flush for non testing purposes
  include/osquery/numeric_monitoring.h
  osquery/numeric_monitoring/numeric_monitoring.cpp
  osquery/numeric_monitoring/tests/numeric_monitoring_tests.cpp
Labels: cla signed

#5155 [Table sanity check] Integration test for the `registry` table
  osquery/tests/integration/tables/registry.cpp
Labels: Windows, cla signed, table, test
