Repository osquery/osquery, pull requests merged in 2018-06, with the labels that each got.

#4451 Updated documentation links back to the osquery website.
  docs/wiki/deployment/debugging.md
  docs/wiki/deployment/file-integrity-monitoring.md
  docs/wiki/deployment/process-auditing.md
  docs/wiki/deployment/yara.md
  docs/wiki/introduction/sql.md
Labels: cla signed

#4472 Fix typo in views example
  docs/wiki/deployment/configuration.md
Labels: cla signed, documentation

#4454 Basic db int type support
  include/osquery/database.h
  osquery/database/database.cpp
  osquery/database/tests/database_tests.cpp
Labels: cla signed

#4476 reworked cmake file split database plugins files
  osquery/database/CMakeLists.txt
  osquery/database/plugins/ephemeral.cpp
  osquery/database/plugins/ephemeral.h
  osquery/database/plugins/sqlite.cpp
  osquery/database/plugins/sqlite.h
  osquery/registry/CMakeLists.txt
Labels: cla signed

#4473 Fix older/broken links
  README.md
Labels: cla signed, documentation

#4418 parent directory function
  osquery/sql/sqlite_filesystem.cpp
Labels: cla signed

#4452 tables: text address arg for SMBIOSParser::tables predicate
  osquery/tables/system/darwin/smbios_tables.cpp
  osquery/tables/system/linux/smbios_tables.cpp
  osquery/tables/system/linux/system_info.cpp
  osquery/tables/system/posix/smbios_utils.cpp
  osquery/tables/system/smbios_utils.h
Labels: cla signed, refactor

#4335 Bundle C++ extensions into a single executable
  CMake/CMakeLibs.cmake
  docs/wiki/development/osquery-sdk.md
  external/CMakeLists.txt
  include/osquery/extensions.h
  osquery/examples/extension_group_example/CMakeLists.txt
  osquery/examples/extension_group_example/src/example.cpp
  osquery/examples/extension_group_example/src/example.h
  tools/codegen/templates/osquery_extension_group_main.cpp.in
Labels: cla signed, extensions, feature, ready for review

#4480 docs: adding note about extensions using RJ
  docs/wiki/development/osquery-sdk.md
Labels: cla signed, documentation, extensions

#4482 build: remove PRODUCT_MOBILE_CORE reference and pin v140 compiler
  osquery/tables/system/windows/os_version.cpp
  tools/build.ps1
Labels: bug, build/test, cla signed

#4423 Rid off the shared_ptr using from config schedule
  include/osquery/config.h
  osquery/config/config.cpp
Labels: bug, cla signed, configuration

#4485 Use std::vector instead of std::list for PackRef in Config
  osquery/config/config.cpp
Labels: cla signed, configuration, ready for review, refactor

#4463 Fixed up resource releasing order UB in `ImplExtensionClient`
  osquery/extensions/impl_fbthrift.cpp
Labels: bug, cla signed, extensions, ready for review

#4484 MAC framework is not a supported KPI
  docs/wiki/deployment/process-auditing.md
Labels: cla signed

#4422 Update docs around the users table to account for Windows
  specs/users.table
Labels: Windows, cla signed, documentation

#4499 Fix Mojave BSSIDs
  osquery/tables/networking/darwin/wifi_survey.mm
Labels: Mojave, cla signed

#4490 rocksDB simplify
  osquery/database/plugins/rocksdb.cpp
Labels: cla signed, database

#4414 Expand the API for the new SQLite functions
  osquery/config/additional_parsers/auto_constructed_tables.cpp
  osquery/sql/sqlite_util.h
  osquery/sql/virtual_sqlite_table.cpp
Labels: SQL, cla signed

#4502 events: updating logging verbiage and off-by-one for powershell events
  osquery/tables/events/windows/powershell_events.cpp
Labels: Windows, bug, cla signed, events

#4489 Ephemeral native support for int
  include/osquery/database.h
  osquery/core/conversions.h
  osquery/database/database.cpp
  osquery/database/plugins/ephemeral.cpp
  osquery/database/plugins/ephemeral.h
  osquery/database/plugins/rocksdb.cpp
  osquery/database/plugins/rocksdb.h
  osquery/database/plugins/sqlite.cpp
  osquery/database/plugins/sqlite.h
Labels: cla signed, database

#4506 get rid of unnecessary string conversion
  osquery/sql/sqlite_hashing.cpp
Labels: cla signed

#4168 Add battery virtual table for Darwin
  osquery/tables/system/darwin/battery.mm
  specs/darwin/battery.table
Labels: cla signed, macOS, needs response, virtual tables

#4510 added git clang format pre-commit hook
  Makefile
  tools/hooks/pre-commit.py
Labels: cla signed

#4509 Move process_event's status to extended schema
  specs/posix/process_events.table
Labels: API change, cla signed, events

#4512 Make gentable.py ignore non *.in template files
  tools/codegen/gentable.py
Labels: bug, cla signed

#4517 If config update call from extension failed, do not go further
  osquery/config/config.cpp
Labels: bug, cla signed, configuration, extensions

#4219 tables: Report process limits on darwin and linux
  osquery/tables/system/posix/ulimit_info.cpp
  specs/posix/ulimit_info.table
Labels: Linux, cla signed, needs response, virtual tables

#4511 Set parent to -1 on process_events
  osquery/tables/events/linux/process_events.cpp
  specs/posix/process_events.table
Labels: API change, cla signed, events

#4508 [Fix 4488] Ensure that corrupted DB entries are processed gracefully
  include/osquery/events.h
  osquery/events/events.cpp
  osquery/events/tests/events_database_tests.cpp
Labels: bug, cla signed, database

#4496 Update provisioning and build scripts to VS2017 (as per #4151)
  .gitignore
  CMakeLists.txt
  tools/build.ps1
  tools/provision.ps1
  tools/provision/chocolatey/osquery_utils.ps1
  tools/vsinstall.json
Labels: Windows, build/test, cla signed

#4525 tables: Fix macOS signature table reporting
  osquery/tables/system/darwin/signature.mm
  specs/darwin/signature.table
Labels: bug, cla signed, macOS, virtual tables

#4528 Registry: don't call external code holding lock
  osquery/registry/registry_interface.cpp
Labels: bug, cla signed

#4530 Do not continue FileOpsTests.* after file opening failure
  osquery/filesystem/tests/fileops_tests.cpp
Labels: build/test, cla signed, debt, ready for review

#4521 Add decode back to cmdline pieces
  osquery/tables/events/linux/process_events.cpp
Labels: cla signed

#4515 bug split(string,string,size_t)
  osquery/core/conversions.cpp
  osquery/core/conversions.h
  osquery/core/tests/conversions_tests.cpp
  osquery/tables/system/linux/md_tables.cpp
  osquery/tables/system/linux/os_version.cpp
  osquery/tables/system/linux/processes.cpp
Labels: bug, cla signed

#4507 base64 encoding and decoding optimized
  osquery/core/conversions.cpp
  osquery/core/conversions.h
Labels: cla signed, performance

#4532 bug: ensure correct checks on OpenProcess handles
  osquery/tables/system/windows/processes.cpp
Labels: Windows, bug, cla signed, in progress

#4531 auditdnetlink: Do not reset the handle when poll() returns EINTR
  osquery/events/linux/auditdnetlink.cpp
Labels: cla signed

#4529 Fix up flaky fileops_tests
  osquery/filesystem/tests/fileops_tests.cpp
Labels: bug, build/test, cla signed, flaky test, ready for review

#4534 Move process namespaces to separate table
  osquery/tables/system/linux/processes.cpp
  specs/linux/process_namespaces.table
  specs/processes.table
Labels: API change, Linux, cla signed

#4544 SQL::selectFrom() pass columns as ref
  include/osquery/sql.h
  osquery/sql/sql.cpp
Labels: cla signed, easy, performance

#4542 Fix comment typos
  osquery/events/pathset.h
  osquery/filesystem/fileops.h
Labels: cla signed, easy

#4543 Removed extra empty line at top of file
  osquery/remote/enroll/plugins/tls_enroll.h
Labels: cla signed, easy

#4535 AuditdNetlink: Only start the netlink services once
  osquery/events/linux/auditdnetlink.cpp
  osquery/events/linux/auditdnetlink.h
  osquery/events/linux/auditeventpublisher.cpp
Labels: Linux, bug, cla signed, process auditing

#4540 ATCPlugin fix ctor initialization order
  osquery/config/additional_parsers/auto_constructed_tables.h
Labels: bug, cla signed, easy

#4539 Git pre-commit hook handle already formatted files
  tools/hooks/pre-commit.py
Labels: bug, cla signed

#4359 Fix autoloaded extension processes outliving the main process
  osquery/core/posix/process.cpp
  osquery/core/watcher.cpp
  osquery/core/watcher.h
Labels: bug, cla signed, extensions

#4549 Remove /dev/null monitoring from fsevents
  osquery/events/darwin/fsevents.cpp
Labels: bug, cla signed, events, macOS

#4541 Catch exceptions by ref on windows processes
  osquery/core/windows/process.cpp
Labels: cla signed, easy, performance

#4550 bug: correctly check windows event log channels for firing
  osquery/events/windows/windows_event_log.cpp
  osquery/tables/events/windows/windows_events.cpp
Labels: Windows, bug, cla signed, events

#4553 deps: Update libxml2 to version 2.9.7
  tools/provision/formula/libxml2.rb
Labels: Linux, cla signed, dependencies, macOS

#4524 Force `osqueryi` to not use osquery extensions from system env in tests.
  tools/tests/test_osqueryi.py
Labels: bug, build/test, cla signed, flaky test, ready for review

#4557 deps: Update yara to version 3.7.1
  tools/provision/formula/yara.rb
  tools/provision/ubuntu.sh
Labels: Linux, cla signed, dependencies, macOS

#4558 Build posix with -fno-limit-debug-info
  CMakeLists.txt
Labels: cla signed

#4568 actualized names for *base64* family functions
  docs/wiki/introduction/sql.md
Labels: SQL, cla signed, documentation, user experience

#4555 deps: Update openssl to version 1.0.2o
  tools/provision/formula/openssl.rb
Labels: Linux, cla signed, dependencies, macOS

#4559 deploy: set default flagfile to utf-8 for MSI package
  tools/deployment/make_windows_package.ps1
Labels: Windows, bug, cla signed, deployment

#4545 InterruptableRunnable RunnerInterruptPoint redesign
  include/osquery/dispatcher.h
  osquery/dispatcher/dispatcher.cpp
  osquery/dispatcher/tests/dispatcher_tests.cpp
  osquery/events/windows/windows_event_log.cpp
  osquery/logger/plugins/tests/buffered_tests.cpp
  osquery/logger/plugins/windows_event_log.cpp
Labels: cla signed

#4570 dispatcher race conditions
  include/osquery/dispatcher.h
  osquery/dispatcher/dispatcher.cpp
Labels: bug, cla signed

#4561 Update brew and formulae for Mojave
  tools/provision.sh
  tools/provision/formula/bzip2.rb
  tools/provision/formula/ccache.rb
  tools/provision/formula/libmagic.rb
  tools/provision/formula/ncurses.rb
  tools/provision/formula/openssl.rb
  tools/provision/formula/python.rb
Labels: Mojave, build/test, cla signed

#4576 tests: ensure service has been installed before starting
  tools/tests/test_windows_service.py
Labels: Jenkins error, Windows, build/test, cla signed

#4572 Removing macOS kernel module
  CMake/CMakeLibs.cmake
  CMake/Packages.cmake
  CMakeLists.txt
  Makefile
  docs/wiki/deployment/process-auditing.md
  docs/wiki/development/building.md
  docs/wiki/development/kernel.md
  kernel/CMakeLists.txt
  kernel/include/feeds.h
  kernel/src/circular_queue_kern.c
  kernel/src/circular_queue_kern.h
  kernel/src/osquery.cpp
  kernel/src/publishers.h
  kernel/src/publishers/darwin/kernel_file_events.c
  kernel/src/publishers/darwin/process_events.c
  kernel/test.sh
  kernel/tools/darwin.sh
  kernel/tools/deployment/Info.plist
  kernel/tools/unload_with_retry.sh
  mkdocs.yml
  osquery/CMakeLists.txt
  osquery/events/CMakeLists.txt
  osquery/events/darwin/kernel_util.cpp
  osquery/events/freebsd/fsevents.h
  osquery/events/freebsd/kernel_util.cpp
  osquery/events/kernel/benchmarks/kernel_communication_benchmarks.cpp
  osquery/events/kernel/circular_queue_user.cpp
  osquery/events/kernel/circular_queue_user.h
  osquery/events/kernel/tests/kernel_communication_tests.cpp
  osquery/events/linux/kernel_util.cpp
  osquery/tables/CMakeLists.txt
  osquery/tables/events/darwin/kernel/process_events.cpp
  osquery/tables/events/darwin/kernel/process_file_events.cpp
  tools/lib.sh
Labels: cla signed, in progress

#4564 update win64 openssl to 1.0.2o
  tools/provision.ps1
  tools/provision/chocolatey/openssl.ps1
Labels: Windows, cla signed, dependencies

#4584 Remove linux undents
  tools/provision/formula/ccache.rb
  tools/provision/formula/fbthrift-mstch.rb
  tools/provision/formula/gcc.rb
  tools/provision/formula/openssl.rb
  tools/provision/formula/python.rb
  tools/provision/formula/zlib-legacy.rb
Labels: Jenkins error, Linux, bug, build/test, cla signed

#4518 Added ntfs acl permissions virtual table
  osquery/tables/system/windows/ntfs_acl_permissions.cpp
  specs/windows/ntfs_acl_permissions.table
Labels: Windows, cla signed, virtual tables

#4590 deps: revert linuxbrew updates from #4561
  tools/provision.sh
Labels: Linux, cla signed, dependencies

#4583 Implement make format_check
  Makefile
  tools/audit.sh
  tools/formatting/format-check.py
Labels: build/test, cla signed

#4477 Updating process auditing documentation
  docs/wiki/deployment/process-auditing.md
Labels: cla signed, documentation, events

#4574 Fix make sync on centos7
  CMakeLists.txt
  tools/sync.sh
Labels: Linux, build/test, cla signed

#4567 Parse structured options as string
  include/osquery/config.h
  osquery/config/parsers/options.cpp
  osquery/config/parsers/tests/options_tests.cpp
Labels: cla signed, configuration, hardening

#4609 Revert homebrew changes introduced for Mojave
  tools/provision.sh
  tools/provision/formula/bzip2.rb
  tools/provision/formula/ccache.rb
  tools/provision/formula/fbthrift-mstch.rb
  tools/provision/formula/gcc.rb
  tools/provision/formula/libmagic.rb
  tools/provision/formula/ncurses.rb
  tools/provision/formula/openssl.rb
  tools/provision/formula/python.rb
  tools/provision/formula/zlib-legacy.rb
Labels: bug, cla signed

#4565 add recovery behavior to osqueryd Windows service
  osquery/main/windows/main.cpp
Labels: Jenkins error, Windows, cla signed, daemon, feature

#4607 Replace unsafe usages of 0 as nullptr
  osquery/core/conversions.h
  osquery/registry/registry_factory.cpp
Labels: cla signed, hardening

#4606 Comment out unused parameter to make linter happy
  osquery/config/parsers/logger.cpp
Labels: cla signed

#4605 Fix include path on status.h
  include/osquery/status.h
Labels: bug, cla signed

#4603 Improve generated TARGETS formatting
  tools/codegen/gentargets.py
Labels: cla signed

#4585 Watcher: Never give up on extensions
  osquery/core/watcher.cpp
Labels: cla signed, extensions

#4586 toIndex simplification
  osquery/events/events.cpp
Labels: cla signed, performance

#4597 memory leak resolve for dispatcher
  include/osquery/dispatcher.h
  osquery/dispatcher/dispatcher.cpp
Labels: cla signed

#4192 Add some more features to the cpuid table.
  osquery/tables/system/cpuid.cpp
Labels: cla signed, needs response, virtual tables

#4589 Used proper names in registry macro instead of obfuscated names
  include/osquery/registry_factory.h
  include/osquery/sdk.h
Labels: cla signed, extensions, ready for review

#4581 xcode support
  CMakeLists.txt
  Makefile
  osquery/CMakeLists.txt
  tools/generate_xcode_project.sh
Labels: cla signed

#4623 do not strip everything for release build
  tools/deployment/make_linux_package.sh
Labels: Linux, build/test, cla signed

#4622 updated another set of cmake files
  osquery/distributed/CMakeLists.txt
  osquery/events/CMakeLists.txt
  osquery/filesystem/CMakeLists.txt
  osquery/logger/CMakeLists.txt
  osquery/remote/CMakeLists.txt
Labels: cla signed

#4617 Do not try to decode/encode utf-8 in python extensions
  osquery/extensions/CMakeLists.txt
Labels: bug, cla signed, extensions, ready for review

#4416 added custom version of realpath function
  CMakeLists.txt
  osquery/core/CMakeLists.txt
  osquery/core/posix/utils.cpp
  osquery/core/utils.h
  osquery/tables/system/darwin/mounts.cpp
  osquery/tables/system/linux/mounts.cpp
  osquery/tables/system/linux/processes.cpp
Labels: bug, cla signed, in progress

#4625 tests: ensure services have been cleared before testing
  tools/tests/test_windows_service.py
Labels: Windows, build/test, cla signed

#4599 udev resource protection
  osquery/events/linux/udev.cpp
Labels: bug, cla signed

#4442 deps: Use static libfl in thrift build
  tools/provision/formula/thrift.rb
Labels: Linux, cla signed, dependencies

#4591 events proof read
  include/osquery/events.h
  osquery/events/events.cpp
Labels: cla signed

#4380 first pass at ssh_config table
  osquery/tables/system/posix/ssh_configs.cpp
  specs/posix/ssh_configs.table
Labels: cla signed, macOS, ready for review, virtual tables

#4579 fix regular files being tagged as symlinks
  osquery/tables/utility/file.cpp
Labels: cla signed

#4594 [Docs] Kafka logging plugin is called kafka_producer not kafka
  docs/wiki/deployment/logging.md
Labels: cla signed, documentation

#4618 The default timestamp was added for shell_history without timestamps
  osquery/tables/system/posix/shell_history.cpp
  osquery/tables/system/posix/shell_history.h
  osquery/tables/system/posix/tests/shell_history_tests.cpp
  specs/posix/shell_history.table
Labels: API change, Linux, bug, cla signed, macOS

#4634 refactor before adding bash_sessions history files to shell_history
  osquery/tables/system/posix/shell_history.cpp
Labels: Linux, cla signed, feature, macOS, refactor

#4638 reworked part of cmake files
  osquery/sql/CMakeLists.txt
  osquery/tables/CMakeLists.txt
  osquery/utils/CMakeLists.txt
Labels: cla signed, refactor

#4637 Remove unused unused mutex 'config_valid_mutex_' from config
  osquery/config/config.cpp
Labels: cla signed, configuration, debt, refactor

#4643 Improved xcode compatibility
  CMakeLists.txt
  tools/generate_xcode_project.sh
Labels: macOS

#4627 Create a `success` and `failure` static factory for Status
  include/osquery/status.h
  osquery/core/CMakeLists.txt
  osquery/core/status.cpp
  osquery/core/tests/status_tests.cpp
Labels: cla signed, debt, ready for review, refactor

#4630 deps: Small changes for Ubuntu18 build
  tools/provision/formula/libgcrypt.rb
  tools/provision/formula/popt.rb
  tools/provision/ubuntu.sh
Labels: Linux, cla signed, dependencies

#4646 Refactor/cmake
  osquery/CMakeLists.txt
  osquery/registry/CMakeLists.txt
  osquery/remote/CMakeLists.txt
  osquery/sql/CMakeLists.txt
Labels: cla signed, cmake, refactor

#4648 Connecte expected.h and error.h tests to build system
  osquery/core/CMakeLists.txt
  osquery/core/tests/error_tests.cpp
Labels: bug, cla signed, ready for review

#4645 Remove platformStrncpy function from osquery/core/utils.h
  osquery/core/posix/utils.cpp
  osquery/core/utils.h
  osquery/core/windows/utils.cpp
Labels: cla signed, ready for review, refactor

#4651 Using TOKEN_USER instead of TOKEN_OWNER struct
  osquery/tables/system/windows/processes.cpp
Labels: Windows, cla signed, virtual tables

#4650 Explicit use `ValueType` and `EnumErrorType` in `Expected` full type definition
  include/osquery/error.h
  include/osquery/expected.h
  osquery/core/tests/error_tests.cpp
  osquery/core/tests/exptected_tests.cpp
Labels: cla signed, feature, refactor

#4629 Add ssdeep table for posix
  CMakeLists.txt
  osquery/sql/sqlite_hashing.cpp
  osquery/sql/tests/sql_tests.cpp
  osquery/tables/CMakeLists.txt
  osquery/tables/system/hash.cpp
  osquery/tables/system/tests/system_tables_tests.cpp
  specs/hash.table
  tools/provision.sh
  tools/provision/formula/ssdeep-cpp.rb
  tools/provision/freebsd.sh
Labels: cla signed
