Repository osquery/osquery, pull requests merged in 2018-09, with the labels that each got.

#5093 build: Set 10.13 as default builder
  Makefile
  README.md
Labels: build, cla signed, macOS, test

#5170 executing query monitor under killswitch
  include/osquery/killswitch.h
  osquery/dispatcher/scheduler.cpp
  osquery/killswitch/killswitch.cpp
Labels: cla signed

#5150 integration test helper NonNegativeOrErrorInt
  osquery/tests/integration/tables/helper.cpp
  osquery/tests/integration/tables/helper.h
Labels: cla signed

#5169 numeric monitoring aggregation types
  include/osquery/numeric_monitoring.h
  osquery/numeric_monitoring/numeric_monitoring.cpp
  osquery/numeric_monitoring/pre_aggregation_cache.cpp
  osquery/numeric_monitoring/tests/pre_aggregation_cache_tests.cpp
Labels: cla signed

#5171 monitor number of times osquery starts
  include/osquery/killswitch.h
  osquery/core/init.cpp
  osquery/killswitch/killswitch.cpp
Labels: cla signed

#5111 intel_me_info/Windows: Fix the buffer size for the GetFirmwareVersion command
  osquery/tables/system/intel_me.hpp
  osquery/tables/system/windows/intel_me.cpp
Labels: cla signed

#5172 total number of queries sent numeric_monitor
  include/osquery/killswitch.h
  osquery/killswitch/killswitch.cpp
  osquery/logger/logger.cpp
Labels: cla signed

#5178 vagrant check memory env variable
  Vagrantfile
Labels: cla signed

#5105 add osquery.man to wix config for New-MsiPackage - #5067
  tools/deployment/make_windows_package.ps1
Labels: Windows, cla signed, deployment

#5183 tables: add pci_class_id and pci_subclass_id to pci_devices
  osquery/tables/system/linux/pci_devices.cpp
  specs/posix/pci_devices.table
Labels: cla signed

#5181 Changing the active code page to United States code
  tools/make-win64-binaries.bat
Labels: Windows, build, cla signed

#5186 Small doc fixes
  docs/wiki/deployment/process-auditing.md
  docs/wiki/development/building.md
Labels: cla signed

#5174 Removing potentially risky method `getOr(T const&)` from `Expected`
  include/osquery/expected.h
  osquery/core/conversions.cpp
  osquery/core/tests/exptected_tests.cpp
  osquery/devtools/shell.cpp
  osquery/events/events.cpp
  osquery/events/linux/auditeventpublisher.cpp
  osquery/tables/networking/windows/arp_cache.cpp
  osquery/tables/networking/windows/interfaces.cpp
  osquery/tables/system/windows/physical_disk_performance.cpp
Labels: API change, cla signed

#5188 osqueryi needs root to test auditing
  docs/wiki/deployment/process-auditing.md
Labels: Linux, cla signed, documentation

#5192 dispatcher static destructor fiasco
  include/osquery/dispatcher.h
  osquery/dispatcher/dispatcher.cpp
Labels: cla signed

#5191 Expected::takeOr have to accept rvalue as an argument
  include/osquery/expected.h
  osquery/core/tests/exptected_tests.cpp
Labels: cla signed, debt

#5179 vagrant configure vmware_desktop
  Vagrantfile
Labels: cla signed

#5190 Remove the rest of the safeStrto* function from conversion.h
  osquery/core/conversions.h
  osquery/core/windows/process_ops.cpp
  osquery/dispatcher/distributed_runner.cpp
  osquery/events/events.cpp
  osquery/events/linux/auditdnetlink.cpp
  osquery/examples/example_writable_table.cpp
  osquery/tables/networking/posix/interfaces.cpp
  osquery/tables/system/darwin/tests/asl_tests.cpp
  osquery/tables/system/windows/objects.cpp
  osquery/tables/system/windows/system_info.cpp
Labels: cla signed, debt

#5189 [Table sanity check] routes & arp_cache
  osquery/tests/integration/tables/arp_cache.cpp
  osquery/tests/integration/tables/helper.cpp
  osquery/tests/integration/tables/helper.h
  osquery/tests/integration/tables/interface_addresses.cpp
  osquery/tests/integration/tables/routes.cpp
Labels: cla signed, table, test

#4903 Add interface_ipv6 table
  osquery/tables/networking/darwin/interface_ip.cpp
  osquery/tables/networking/freebsd/interface_ip.cpp
  osquery/tables/networking/linux/interface_ip.cpp
  osquery/tables/networking/posix/interfaces.h
  osquery/tests/integration/tables/CMakeLists.txt
  osquery/tests/integration/tables/interface_ipv6.cpp
  specs/posix/interface_ipv6.table
Labels: FreeBSD, Linux, cla signed, macOS, table

#5182 Add ReleaseDate to table for platform_info queries on Windows
  osquery/core/windows/wmi.cpp
  osquery/core/windows/wmi.h
  osquery/tables/system/windows/smbios_tables.cpp
Labels: Windows, bug, cla signed, virtual tables

#5208 boost throwing is_directory bug
  osquery/filesystem/windows/fileops.cpp
Labels: Windows, bug, cla signed

#5193 Add a 'permission' field to the chrome_extensions table
  osquery/tables/applications/browser_utils.cpp
  specs/chrome_extensions.table
Labels: API change, cla signed

#5206 Non throwing directory creation function.
  include/osquery/filesystem.h
  osquery/filesystem/filesystem.cpp
  osquery/filesystem/tests/filesystem_tests.cpp
Labels: cla signed, feature

#5207 Prepare the filesystem directories in initialisation routine
  osquery/core/init.cpp
Labels: bug, cla signed

#5209 Create helper functions to get CPU cores info on linux
  osquery/core/CMakeLists.txt
  osquery/core/linux/cpu.cpp
  osquery/core/linux/cpu.h
  osquery/core/linux/tests/cpu_test.cpp
Labels: Linux, cla signed, feature

#5204 numeric_monitoring recursive sync record
  include/osquery/numeric_monitoring.h
  osquery/numeric_monitoring/numeric_monitoring.cpp
  osquery/numeric_monitoring/plugin_interface.cpp
  osquery/numeric_monitoring/plugin_interface.h
  osquery/numeric_monitoring/plugins/filesystem.cpp
  osquery/numeric_monitoring/plugins/tests/filesystem_tests.cpp
  osquery/numeric_monitoring/tests/numeric_monitoring_tests.cpp
Labels: cla signed, feature

#5187 posix profiling
  include/osquery/killswitch.h
  osquery/CMakeLists.txt
  osquery/dispatcher/scheduler.cpp
  osquery/killswitch/killswitch.cpp
  osquery/profiler/CMakeLists.txt
  osquery/profiler/posix/profiler.cpp
  osquery/profiler/profiler.h
  osquery/profiler/windows/profiler.cpp
Labels: cla signed, ready for review

#5215 chrome_extensions: Use the translation dictionary with case insensitive keys
  osquery/tables/applications/browser_utils.cpp
Labels: bug, cla signed, macOS

#5217 tables: netmask should be an integer
  osquery/tables/networking/windows/routes.cpp
  osquery/tests/integration/tables/routes.cpp
  specs/routes.table
Labels: Windows, cla signed, hardening

#5112 added database migration class
  osquery/core/CMakeLists.txt
  osquery/core/database/rocksdb_migration.cpp
  osquery/core/database/rocksdb_migration.h
Labels: cla signed, refactor

#4832 database: changing default path of the database for pathing uniformity
  include/osquery/core.h
  osquery/core/init.cpp
  osquery/database/database.cpp
  osquery/extensions/extensions.cpp
  osquery/main/windows/main.cpp
  osquery/tables/yara/yara_utils.h
Labels: cla signed, database, ready for review

#5221 remove old boost bug support
  osquery/core/init.cpp
Labels: cla signed

#5226 Add InstallDate to os_version for Windows
  osquery/tables/system/windows/os_version.cpp
  osquery/tests/integration/tables/os_version.cpp
  specs/os_version.table
Labels: API change, Windows, cla signed, virtual tables

#5224 Add per process performance data to windows processes table
  osquery/tables/system/windows/processes.cpp
  osquery/tables/utility/time.cpp
  specs/processes.table
  specs/utility/time.table
Labels: Windows, cla signed, performance, ready for review

#5229 bug: explicitly set safe permissions on osquery dbs
  osquery/database/plugins/rocksdb.cpp
  osquery/database/plugins/sqlite.cpp
  osquery/dispatcher/scheduler.cpp
  osquery/filesystem/fileops.h
  osquery/filesystem/posix/fileops.cpp
  osquery/filesystem/tests/fileops_tests.cpp
  osquery/filesystem/windows/fileops.cpp
Labels: Windows, bug, cla signed, database
