Repository osquery/osquery, pull requests merged in 2018-07, with the labels that each got.

#4656 Remove container specific join implementation from conversions.h
  osquery/core/conversions.cpp
  osquery/core/conversions.h
Labels: cla signed, debt, performance

#4246 Add a hash_resources parameter (column) to the macOS signature table
  osquery/tables/system/darwin/signature.mm
  osquery/tables/system/darwin/tests/signature_tests.mm
  specs/darwin/signature.table
Labels: cla signed, macOS, virtual tables

#4636 Update win64 openssl provisioning script
  tools/build.ps1
  tools/provision/chocolatey/openssl.ps1
  tools/provision/chocolatey/osquery_utils.ps1
Labels: cla signed

#4661 Initd script
  tools/deployment/make_linux_package.sh
  tools/deployment/osqueryd.initd
Labels: Linux, cla signed, deployment

#4665 Created an `enum ConversionError` for conversion errors
  osquery/core/conversions.h
  osquery/core/tests/conversions_tests.cpp
Labels: cla signed, feature

#4664 deps: reinstall for portable gcc and mojave support
  tools/provision.sh
  tools/provision/formula/Abstract/abstract-osquery-formula.rb
  tools/provision/formula/aws-sdk-cpp.rb
  tools/provision/formula/bzip2.rb
  tools/provision/formula/ccache.rb
  tools/provision/formula/cmake.rb
  tools/provision/formula/fbthrift-double-conversion.rb
  tools/provision/formula/fbthrift-mstch.rb
  tools/provision/formula/gcc.rb
  tools/provision/formula/libmagic.rb
  tools/provision/formula/ncurses.rb
  tools/provision/formula/openssl.rb
  tools/provision/formula/python.rb
  tools/provision/formula/thrift.rb
  tools/provision/formula/zlib-legacy.rb
Labels: Linux, cla signed, dependencies, macOS

#4669 Confusing comment correction
  include/osquery/expected.h
Labels: cla signed

#4670 Output stream operator `<<` for `Error`
  include/osquery/error.h
  osquery/core/tests/error_tests.cpp
Labels: cla signed, feature

#4668 Adding OSX Dummy malware to osx-attacks query pack
  packs/osx-attacks.conf
Labels: cla signed, macOS, packs

#4673 Add documentation for conditional column gen
  docs/wiki/development/creating-tables.md
Labels: cla signed, documentation

#4431 Fixing user_time, system_time bug and changing the cpu utilization logic
  osquery/CMakeLists.txt
  osquery/core/tests/watcher_tests.cpp
  osquery/core/watcher.cpp
  osquery/tables/system/linux/processes.cpp
  osquery/tables/system/tests/system_tables_tests.cpp
  osquery/tables/system/windows/processes.cpp
  specs/processes.table
Labels: cla signed

#4684 bug: Fix SELinux events rebase
  osquery/tables/events/linux/selinux_events.cpp
Labels: bug, cla signed, unbreak now

#4626 Numeric monitoring system concept
  include/osquery/numeric_monitoring.h
  osquery/CMakeLists.txt
  osquery/core/init.cpp
  osquery/numeric_monitoring/CMakeLists.txt
  osquery/numeric_monitoring/numeric_monitoring.cpp
  osquery/numeric_monitoring/plugin_interface.cpp
  osquery/numeric_monitoring/plugin_interface.h
  osquery/numeric_monitoring/plugins/filesystem.cpp
  osquery/numeric_monitoring/plugins/filesystem.h
  osquery/numeric_monitoring/plugins/tests/filesystem_tests.cpp
  osquery/numeric_monitoring/tests/numeric_monitoring_tests.cpp
Labels: cla signed, extensions, feature, ready for review

#4685 Remove using instance() from serviceCount()
  include/osquery/dispatcher.h
  osquery/dispatcher/dispatcher.cpp
Labels: cla signed, hardening

#4688 Fix documentation for flag decorations_top_level
  docs/wiki/deployment/configuration.md
Labels: bug, cla signed, documentation

#4678 Add the ability to specify file_paths with sql queries
  docs/wiki/deployment/file-integrity-monitoring.md
  osquery/config/parsers/file_paths.cpp
Labels: cla signed

#4682 flags: Separate flags and flagalias
  include/osquery/flags.h
  osquery/config/config.cpp
  osquery/core/flagalias.h
  osquery/core/flags.cpp
  osquery/core/tests/flags_tests.cpp
  osquery/database/database.cpp
  osquery/extensions/extensions.cpp
  osquery/logger/logger.cpp
  osquery/logger/plugins/filesystem_logger.cpp
Labels: cla signed, debt

#4692 Unbreak build against Boost 1.68
  osquery/core/conversions.cpp
Labels: cla signed

#4693 Add tests for file_paths_query
  osquery/config/parsers/file_paths.cpp
  osquery/config/parsers/tests/file_paths_tests.cpp
  tools/tests/test_parse_items.conf
Labels: cla signed

#4677 Pre-aggregation cache implementation for numeric monitoring plugins
  osquery/numeric_monitoring/CMakeLists.txt
  osquery/numeric_monitoring/plugin_interface.cpp
  osquery/numeric_monitoring/pre_aggregation_cache.cpp
  osquery/numeric_monitoring/pre_aggregation_cache.h
  osquery/numeric_monitoring/tests/pre_aggregation_cache_tests.cpp
Labels: cla signed, feature, ready for review

#4681 logger: Fix logfile writes to /tmp with verbose flag
  osquery/logger/logger.cpp
Labels: bug, cla signed, logging

#4667 Add unique pid field to the processes table on macOS
  osquery/tables/system/darwin/processes.cpp
  specs/processes.table
Labels: cla signed, feature, in progress, macOS, virtual tables

#4696 round negative reported durations in query profiler to zero
  tools/tests/utils.py
Labels: build/test, cla signed

#4695 fixed error when wrong directory separator was used for parent_directory function
  osquery/sql/sqlite_filesystem.cpp
Labels: cla signed

#4701 Fixed up misspells in variable name and docstrings
  osquery/numeric_monitoring/pre_aggregation_cache.cpp
  osquery/numeric_monitoring/pre_aggregation_cache.h
Labels: cla signed, debt, easy, ready for review

#4686 Add etc/hosts.ics data to the etc_hosts table.
  osquery/tables/networking/etc_hosts.cpp
  osquery/tables/networking/tests/networking_tables_tests.cpp
  osquery/tests/test_util.cpp
  osquery/tests/test_util.h
  tools/tests/test_hosts_ics.txt
Labels: Windows, cla signed, virtual tables

#4689 Implement generic `tryTo` for string to boolean converions
  osquery/core/conversions.cpp
  osquery/core/conversions.h
  osquery/core/tests/conversions_tests.cpp
  osquery/devtools/shell.cpp
  osquery/tables/applications/browser_utils.h
Labels: API change, cla signed, ready for review, refactor

#4647 Improving audit-based table performances
  include/osquery/database.h
  include/osquery/events.h
  osquery/database/database.cpp
  osquery/database/plugins/ephemeral.cpp
  osquery/database/plugins/ephemeral.h
  osquery/database/plugins/rocksdb.cpp
  osquery/database/plugins/rocksdb.h
  osquery/database/plugins/sqlite.cpp
  osquery/database/plugins/sqlite.h
  osquery/database/tests/database_tests.cpp
  osquery/database/tests/plugin_tests.cpp
  osquery/database/tests/plugin_tests.h
  osquery/events/benchmarks/events_benchmarks.cpp
  osquery/events/events.cpp
  osquery/events/linux/auditdnetlink.cpp
  osquery/events/linux/auditdnetlink.h
  osquery/events/linux/auditeventpublisher.cpp
  osquery/events/tests/events_database_tests.cpp
  osquery/tables/events/linux/process_events.cpp
  osquery/tables/events/linux/process_file_events.cpp
  osquery/tables/events/linux/socket_events.cpp
  osquery/tables/events/linux/user_events.cpp
Labels: cla signed

#4676 `tryTo<>` generics for string to integer conversion
  osquery/core/conversions.h
  osquery/core/tests/conversions_tests.cpp
  osquery/database/plugins/rocksdb.cpp
  osquery/database/plugins/sqlite.cpp
Labels: API change, cla signed, refactor

#4687 disk_encryption macOS, fix for issue #4479
  osquery/tables/system/darwin/disk_encryption.mm
  osquery/tables/system/linux/disk_encryption.cpp
  specs/posix/disk_encryption.table
Labels: API change, RFC, cla signed

#4133 General SMART drive information virtual table
  CMake/CMakeLibs.cmake
  CMakeLists.txt
  docs/wiki/development/building.md
  osquery/tables/CMakeLists.txt
  osquery/tables/smart/smart_drives.cpp
  osquery/tables/smart/smart_drives.h
  osquery/tables/smart/tests/smart_drives_tests.cpp
  specs/smart/smart_drive_info.table
  tools/codegen/genapi.py
  tools/codegen/genwebsitejson.py
  tools/provision.sh
  tools/provision/formula/libsmartctl.rb
Labels: Linux, cla signed, dependencies, ready for review, virtual tables

#4675 Add support for getting ethernet link speeds for non-linux posix
  osquery/tables/networking/posix/interfaces.cpp
  specs/interface_details.table
Labels: cla signed

#4679 Support CDHash algorithms other than SHA-1 (Darwin)
  osquery/tables/system/darwin/signature.mm
  specs/darwin/signature.table
Labels: cla signed

#4683 tables: Remove lexical_cast include from tables
  include/osquery/tables.h
  osquery/config/config.cpp
  osquery/core/tables.cpp
  osquery/core/tests/watcher_tests.cpp
  osquery/core/watcher.cpp
  osquery/remote/enroll/plugins/tls_enroll.cpp
  osquery/sql/sqlite_util.cpp
  osquery/sql/virtual_table.cpp
  osquery/tables/events/darwin/disk_events.cpp
  osquery/tables/system/cpuid.cpp
  osquery/tables/system/darwin/preferences.cpp
  osquery/tables/system/darwin/signature.mm
  osquery/tables/system/freebsd/os_version.cpp
  osquery/tables/system/linux/os_version.cpp
  osquery/tables/system/linux/processes.cpp
  osquery/tables/system/posix/shell_history.cpp
  osquery/tables/system/posix/suid_bin.cpp
  osquery/tables/system/windows/logged_in_users.cpp
Labels: cla signed, debt, ready for review, virtual tables

#4709 Compression/decompression silent error
  osquery/filesystem/file_compression.cpp
  osquery/filesystem/fileops.h
Labels: bug, cla signed

#4707 remove old version of schedule from the codebase and tests
  osquery/config/config.cpp
  osquery/tables/system/darwin/block_devices.cpp
  osquery/tables/system/darwin/smbios_tables.cpp
  tools/tests/test.badconfig
  tools/tests/test.config
  tools/tests/test.config.d/osquery.conf
  tools/tests/utils.py
Labels: API change, cla signed, debt

#4613 Windows file ops
  osquery/core/windows/process_ops.cpp
  osquery/filesystem/fileops.h
  osquery/filesystem/windows/fileops.cpp
  osquery/tables/utility/file.cpp
  specs/utility/file.table
Labels: Windows, cla signed, virtual tables

#4699 Adding content_caching to sharing_preferences
  osquery/tables/system/darwin/sharing_preferences.cpp
  specs/darwin/sharing_preferences.table
Labels: cla signed, macOS, virtual tables

#4690 Use pre-aggregation cache for all records flowing thru numeric monitoring system
  docs/wiki/installation/cli-flags.md
  include/osquery/numeric_monitoring.h
  osquery/numeric_monitoring/numeric_monitoring.cpp
  osquery/numeric_monitoring/tests/numeric_monitoring_tests.cpp
Labels: cla signed, feature, ready for review

#4094 Write support for tables implemented from extensions
  include/osquery/mutex.h
  include/osquery/tables.h
  osquery/core/tables.cpp
  osquery/devtools/shell.cpp
  osquery/examples/example_writable_table.cpp
  osquery/registry/registry_interface.cpp
  osquery/sql/benchmarks/sql_benchmarks.cpp
  osquery/sql/sqlite_util.cpp
  osquery/sql/tests/virtual_table_tests.cpp
  osquery/sql/virtual_table.cpp
  osquery/sql/virtual_table.h
Labels: cla signed, extensions, feature, needs response

#4719 Remove useless include of <iostream> from status.h
  osquery/core/status.cpp
Labels: bug, cla signed, ready for review

#4717 Add missed semicolon to `utils.cpp`
  osquery/core/posix/utils.cpp
Labels: bug, cla signed, ready for review

#4716 Use `tryTo` instead of `safeStrtoull` in the code
  osquery/core/conversions.cpp
  osquery/core/conversions.h
  osquery/tables/networking/windows/interfaces.cpp
  osquery/tables/system/windows/physical_disk_performance.cpp
Labels: cla signed, debt, ready for review, refactor

#4715 Add socket_designation to CPU info
  osquery/tables/system/windows/cpu_info.cpp
  specs/windows/cpu_info.table
Labels: API change, Windows, cla signed, feature

#4726 Revert regression on symlink detection
  osquery/tables/utility/file.cpp
Labels: bug, cla signed

#4671 disable malfunctioning new features on the fly using killswitch
  include/osquery/killswitch.h
  osquery/CMakeLists.txt
  osquery/config/config.cpp
  osquery/config/plugins/filesystem_config.cpp
  osquery/config/plugins/tls_config.cpp
  osquery/core/conversions.cpp
  osquery/core/init.cpp
  osquery/core/json.h
  osquery/killswitch/CMakeLists.txt
  osquery/killswitch/killswitch.cpp
  osquery/killswitch/killswitch_plugin.cpp
  osquery/killswitch/killswitch_plugin.h
  osquery/killswitch/killswitch_refreshable_plugin.cpp
  osquery/killswitch/killswitch_refreshable_plugin.h
  osquery/killswitch/plugins/killswitch_filesystem.cpp
  osquery/killswitch/plugins/killswitch_filesystem.h
  osquery/killswitch/plugins/killswitch_tls.cpp
  osquery/killswitch/plugins/killswitch_tls.h
  osquery/killswitch/plugins/tests/killswitch_filesystem_tests.cpp
  osquery/killswitch/tests/killswitch_tests.cpp
  tools/tests/test_killswitch.conf
Labels: RFC, cla signed, ready for review

#4728 incorrect assumption about reserve behavior
  osquery/database/database.cpp
  osquery/events/events.cpp
  osquery/events/linux/auditdnetlink.cpp
  osquery/events/linux/auditeventpublisher.cpp
  osquery/tables/events/linux/process_events.cpp
  osquery/tables/events/linux/process_file_events.cpp
  osquery/tables/events/linux/socket_events.cpp
  osquery/tables/events/linux/user_events.cpp
Labels: bug, cla signed

#4727 get rid of unnecessary ptree includes
  include/osquery/plugin.h
  include/osquery/tables.h
  osquery/carver/carver.cpp
  osquery/carver/tests/carver_tests.cpp
  osquery/config/parsers/events_parser.cpp
  osquery/config/parsers/file_paths.cpp
  osquery/config/plugins/tests/tls_config_tests.cpp
  osquery/config/plugins/tls_config.cpp
  osquery/config/tests/config_tests.cpp
  osquery/database/tests/results_tests.cpp
  osquery/distributed/plugins/tls_distributed.cpp
  osquery/distributed/tests/distributed_tests.cpp
  osquery/events/linux/syslog.cpp
  osquery/events/linux/syslog.h
  osquery/filesystem/tests/filesystem_tests.cpp
  osquery/logger/logger.cpp
  osquery/logger/plugins/tests/tls_logger_tests.cpp
  osquery/logger/plugins/tls_logger.cpp
  osquery/registry/plugin.cpp
  osquery/remote/enroll/enroll.cpp
  osquery/remote/enroll/plugins/tests/tls_enroll_tests.cpp
  osquery/tables/applications/browser_chrome.cpp
  osquery/tables/applications/browser_utils.cpp
  osquery/tables/applications/browser_utils.h
  osquery/tables/applications/posix/browser_opera.cpp
  osquery/tables/applications/windows/carbon_black.cpp
  osquery/tables/system/darwin/asl_utils.cpp
  osquery/tables/system/darwin/asl_utils.h
  osquery/tables/system/darwin/gatekeeper.cpp
  osquery/tables/system/darwin/homebrew_packages.cpp
  osquery/tables/system/darwin/sharing_preferences.cpp
  osquery/tables/system/darwin/tests/asl_tests.cpp
  osquery/tables/system/freebsd/pkg_packages.cpp
  osquery/tables/yara/yara_utils.h
  osquery/tests/test_util.h
Labels: cla signed, debt

#4734 Remove unused includes and forward declaration from core/utils.h
  osquery/core/posix/utils.cpp
  osquery/core/utils.h
  osquery/core/windows/utils.cpp
Labels: cla signed, debt, ready for review

#4733 Add missed include <climits> for PATH_MAX
  osquery/core/posix/utils.cpp
Labels: FreeBSD, Linux, bug, cla signed, ready for review

#4706 Explicitly delete rvalue ref-qualified unconditional access methods from Expected
  include/osquery/expected.h
Labels: cla signed, hardening, ready for review

#4711 Remove dead code from conversions module
  osquery/core/conversions.h
  osquery/core/tests/conversions_tests.cpp
Labels: cla signed, dead code, ready for review, refactor

#4464 [posix] Properly format IPv6 addresses with scopes
  osquery/tables/networking/posix/utils.cpp
Labels: API change, bug, cla signed

#4736 udev fd check
  osquery/events/linux/udev.cpp
Labels: cla signed

#4732 objective c leak
  osquery/filesystem/darwin/plist.mm
Labels: cla signed, macOS, memory leak

#4710 cleanup: Migrate calls to tryTo from 4683
  osquery/config/config.cpp
  osquery/core/tables.cpp
  osquery/core/watcher.cpp
  osquery/sql/virtual_table.cpp
  osquery/tables/system/darwin/signature.mm
  osquery/tables/system/linux/processes.cpp
Labels: bug, cla signed, refactor

#4725 to<Status>(const Expected&) implementation
  include/osquery/status.h
  osquery/core/tests/status_tests.cpp
Labels: cla signed, feature, ready for review

#4746 profile implicit shutdown
  osquery/main/main.cpp
Labels: bug, memory leak

#4295 Add labels for threads
  include/osquery/dispatcher.h
  include/osquery/system.h
  osquery/carver/carver.cpp
  osquery/config/config.cpp
  osquery/core/system.cpp
  osquery/core/watcher.cpp
  osquery/dispatcher/distributed_runner.cpp
  osquery/dispatcher/scheduler.cpp
  osquery/events/darwin/diskarbitration.cpp
  osquery/events/darwin/diskarbitration.h
  osquery/events/darwin/event_taps.cpp
  osquery/events/darwin/event_taps.h
  osquery/events/darwin/fsevents.cpp
  osquery/events/darwin/fsevents.h
  osquery/events/darwin/iokit.cpp
  osquery/events/darwin/iokit.h
  osquery/events/darwin/openbsm.cpp
  osquery/events/darwin/openbsm.h
  osquery/events/darwin/scnetwork.cpp
  osquery/events/darwin/scnetwork.h
  osquery/extensions/extensions.cpp
  osquery/extensions/interface.cpp
  osquery/logger/plugins/buffered.cpp
Labels: API change, cla signed, ready for review, refactor

#4749 setThreadName boilerplate removal
  osquery/carver/carver.cpp
  osquery/config/config.cpp
  osquery/core/watcher.cpp
  osquery/dispatcher/dispatcher.cpp
  osquery/dispatcher/distributed_runner.cpp
  osquery/dispatcher/scheduler.cpp
  osquery/events/darwin/diskarbitration.cpp
  osquery/events/darwin/event_taps.cpp
  osquery/events/darwin/fsevents.cpp
  osquery/events/darwin/iokit.cpp
  osquery/events/darwin/openbsm.cpp
  osquery/events/darwin/scnetwork.cpp
  osquery/events/events.cpp
  osquery/extensions/extensions.cpp
  osquery/extensions/interface.cpp
  osquery/logger/plugins/buffered.cpp
  osquery/sql/benchmarks/sql_benchmarks.cpp
Labels: cla signed

#4747 Fix up naming style for the Expected methods takeOr and getOr
  include/osquery/expected.h
  osquery/core/conversions.cpp
  osquery/core/tests/exptected_tests.cpp
  osquery/core/watcher.cpp
  osquery/devtools/shell.cpp
  osquery/tables/networking/windows/interfaces.cpp
  osquery/tables/system/darwin/signature.mm
  osquery/tables/system/windows/physical_disk_performance.cpp
Labels: cla signed, debt

#4739 Profile scheduled queries using numeric monitoring plugins
  osquery/dispatcher/scheduler.cpp
Labels: cla signed, feature, performance, scheduler

#4756 Handle expect in test
  osquery/killswitch/plugins/tests/killswitch_filesystem_tests.cpp
Labels: cla signed

#4751 Move code of conduct to its own file
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: cla signed, documentation

#4759 Prefer /etc/os-release to identify Arch Linux
  tools/get_platform.py
Labels: Linux, build/test, cla signed

#4743 review: Small code review fixes related to CMake
  CMakeLists.txt
  osquery/core/json.h
  osquery/examples/example_writable_table.cpp
  osquery/killswitch/killswitch_refreshable_plugin.h
  osquery/killswitch/plugins/killswitch_filesystem.h
  osquery/tables/system/darwin/crashes.cpp
  osquery/tables/system/darwin/kernel_panics.cpp
  osquery/tables/yara/yara_utils.h
Labels: build/test, cla signed

#4762 build: gating osquery build hosts to VS 2015 builds
  tools/build.ps1
Labels: Windows, build/test, cla signed

#4754 Remove `safeStrtoll` from conversions.h and change all use cases to `tryTo<>`
  osquery/config/config.cpp
  osquery/core/conversions.h
  osquery/events/events.cpp
  osquery/events/linux/auditeventpublisher.cpp
  osquery/sql/virtual_table.cpp
  osquery/tables/system/linux/processes.cpp
  osquery/tables/system/linux/smbios_tables.cpp
  osquery/tables/system/tests/system_tables_tests.cpp
Labels: cla signed, debt, ready for review

#4764 LoggerDisabler dead code
  osquery/logger/logger.cpp
Labels: cla signed, dead code

#4702 Add cpu architectures for running processes on macOS
  osquery/tables/system/darwin/processes.cpp
  osquery/tables/system/darwin/tests/processes_tests.cpp
  specs/processes.table
Labels: cla signed, feature, macOS

#4763 Avoid verbosity of compiler complains in case of incorrect type for Expected value
  include/osquery/expected.h
Labels: cla signed, debt, easy, feature

#4769 Update autoexec.table
  specs/windows/autoexec.table
Labels: cla signed

#4660 Added a new table for Windows Logon Sessions
  osquery/CMakeLists.txt
  osquery/tables/system/windows/logon_sessions.cpp
  specs/windows/logon_sessions.table
Labels: Windows, cla signed, needs response, virtual tables

#4547 querying of named objects in windows across terminal services sessions. even mutexes.
  osquery/core/CMakeLists.txt
  osquery/core/conversions.h
  osquery/core/windows/handle.cpp
  osquery/core/windows/handle.h
  osquery/core/windows/ntapi.h
  osquery/tables/system/windows/objects.cpp
  specs/windows/winbaseobj.table
Labels: Windows, cla signed, needs response, virtual tables

#4774 `Expected::isValue` method, to make checks 'if expected is not an error then...'
  include/osquery/expected.h
  osquery/core/tests/exptected_tests.cpp
  osquery/events/linux/auditeventpublisher.cpp
  osquery/tables/applications/browser_utils.h
Labels: cla signed, easy, feature, ready for review

#4776 Fix up warning about [missing-braces] in load_average.cpp
  osquery/tables/system/posix/load_average.cpp
Labels: cla signed, debt, easy, ready for review

#4766 performance: construct cache for windows drivers image path
  osquery/tables/system/windows/drivers.cpp
Labels: Windows, cla signed, performance, virtual tables

#4770 perf: setting priority levels to background of osqueryd and children
  osquery/core/init.cpp
  osquery/core/windows/process.cpp
  osquery/core/windows/process_ops.cpp
Labels: Windows, cla signed, performance

#4744 pvs-studio errors and warnings fix
  osquery/core/system.cpp
  osquery/filesystem/filesystem.cpp
  osquery/sql/sqlite_util.cpp
  osquery/sql/virtual_table.cpp
  osquery/tables/system/darwin/authorizations.mm
  osquery/tables/system/darwin/smc_keys.cpp
  osquery/utils/aws_util.cpp
Labels: bug, cla signed, dead code, ready for review

#4780 Resize size check dead code
  osquery/events/linux/auditdnetlink.cpp
  osquery/tables/system/windows/authenticode.cpp
Labels: cla signed, dead code
