Repository osquery/osquery, pull requests merged in 2019-06, with the labels that each got.

#5579 deploy: updating MSI package to install to Program Files
  tools/deployment/make_windows_package.ps1
Labels: cla signed

#5580 windows: updating more references to osquery installation path
  docs/wiki/deployment/configuration.md
  docs/wiki/deployment/logging.md
  osquery/utils/config/default_paths.h
  tools/deployment/chocolatey/tools/chocolateyinstall.ps1
  tools/deployment/osquery.example.conf
  tools/wel/osquery.man
Labels: cla signed

#5590 release: prepping for osquery 3.4.0 release on Windows
  .gitignore
  BUILD.md
  tools/buckconfigs/base.bcfg
  tools/buckconfigs/windows-x86_64/base.bcfg
  tools/buckconfigs/windows-x86_64/toolchain/vs2017_15.5.bcfg
  tools/generate_buck_config.ps1
Labels: Windows, deployment

#5592 macos: Add hack for boost asio string_view detection
  osquery/remote/http_client.cpp
  osquery/remote/http_client.h
  osquery/tables/applications/posix/docker.cpp
Labels: bug, macOS

#5603 Initial codeowners
  CODEOWNERS
Labels: documentation

#5576 Fixing port logic
  osquery/remote/http_client.cpp
Labels: bug, cla signed, networking

#5610 Merge Azure Pipelines build and test jobs
  azure-pipelines.yml
Labels: build, test

#5612 Improve the downloader.py script to use urllib2
  tools/cmake/downloader.py
Labels: build

#5607 Add Azure Pipelines status badges to the README
  README.md
Labels: documentation, test

#5613 Fix tests output and yaml formatting for Azure Pipelines
  azure-pipelines.yml
Labels: test
