Repository osquery/osquery, pull requests merged in 2019-07, with the labels that each got.

#5621 Fix wrong error code returned when querying the Windows registry
  osquery/tables/system/windows/registry.cpp
  tests/unit/tables/system/windows/registry_tests.cpp
Labels: Windows, test

#5623 buck: fixing up buck config generation script for use on Windows
  tools/generate_buck_config.ps1
Labels: Windows, build

#5626 Enable Debug builds on the CI
  azure-pipelines.yml
  cmake/options.cmake
  cmake/utilities.cmake
Labels: build, test

#5627 Explicitly add BUILD_TESTING CMake option
  cmake/options.cmake
Labels: build, test

#5632 Add buck builds on Azure Pipelines
  .travis.yml
  azure-pipelines.yml
Labels: buck, build

#5606 Replacing sync calls by async ones and some cleanup
  osquery/remote/http_client.cpp
  osquery/remote/http_client.h
Labels: merge with rebase, networking

#5633 Fix ATC mounting of SQLite DBs using WAL journaling
  osquery/sql/sqlite_util.h
  osquery/sql/virtual_sqlite_table.cpp
  plugins/config/parsers/auto_constructed_tables.cpp
Labels: feature, needs response

#5637 crontab testcase fix
  tests/integration/tables/crontab.cpp
Labels: bug, table, test

#5467 Change MSI Service Error handling
  tools/deployment/make_windows_package.ps1
Labels: Windows, bug, cla signed, packaging

#5650 Don't return a battery row, if there are no results
  osquery/tables/system/darwin/battery.mm
Labels: macOS, virtual tables

#5630 Improve osquery version detection
  cmake/globals.cmake
  cmake/options.cmake
  cmake/packaging.cmake
  cmake/utilities.cmake
  osquery/utils/info/CMakeLists.txt
Labels: build

#5658 rpm: Check for glibc version and librpm secure_getenv
  osquery/tables/system/linux/rpm_packages.cpp
Labels: Linux, virtual tables

#5653 Specify compiler versions supported in BUILD.md
  BUILD.md
Labels: documentation

#5657 Remove cloud tables from windows
  osquery/tables/CMakeLists.txt
  osquery/tables/cloud/CMakeLists.txt
Labels: Windows, virtual tables

#5666 Fix tables.h hyperlink in docs
  docs/wiki/development/creating-tables.md
Labels: documentation

#5673 Fix python detection on Azure Pipelines
  azure-pipelines.yml
Labels: buck, build
