Repository osquery/osquery, pull requests merged in 2020-08, with the labels that each got.

#6572 fix for md_devices.table issue
  specs/linux/md_devices.table
Labels: documentation, virtual tables

#6569 Fix readFile to observe requested read size
  osquery/filesystem/filesystem.cpp
  osquery/filesystem/tests/filesystem.cpp
Labels: bug

#6555 events: Memoize EventFactory::getType
  osquery/events/tests/events_tests.cpp
  osquery/include/osquery/events.h
Labels: events, performance

#6554 CMake detect MAJOR_IN_SYSMACROS/MKDEV for librpm
  libraries/cmake/source/librpm/CMakeLists.txt
Labels: Linux, build

#6576 ci: Fix pip upgrade warning
  azure-pipelines.yml
Labels: test infra failure

#6575 Move the Windows Events Log parser methods
  osquery/events/CMakeLists.txt
  osquery/events/windows/windowseventlogparser.cpp
  osquery/events/windows/windowseventlogparser.h
  osquery/events/windows/windowseventlogparserservice.cpp
  osquery/events/windows/windowseventlogparserservice.h
  osquery/tables/events/tests/windows/powershell_events_tests.cpp
  osquery/tables/events/tests/windows/windows_events_tests.cpp
  osquery/tables/events/windows/windows_events.cpp
  osquery/tables/events/windows/windows_events.h
Labels: Windows, events, refactor

#6579 Fix call to LocalFree() on uninit ptr inside getUidFromSid()
  osquery/process/windows/process_ops.cpp
Labels: Windows, bug

#6578 Fix incorrect readFile params in createPidFile
  osquery/core/system.cpp
Labels: bug

#6584 powershell_events: Fix bool type usage
  osquery/tables/events/windows/powershell_events.cpp
Labels: Windows, events

#6590 Manual copyright changes
  README.md
  cmake/packaging.cmake
  docs/README.md
  docs/doxygen/mainpage.md
  docs/wiki/development/creating-tables.md
  osquery/core/plugins/sql.cpp
  osquery/core/plugins/sql.h
  osquery/devtools/devtools.h
  osquery/devtools/shell.cpp
  osquery/extensions/thrift/osquery.thrift
  osquery/tables/system/efi_misc.h
  osquery/tables/system/linux/portage.cpp
  osquery/tables/system/windows/kva_speculative_info.cpp
  specs/curl.table
  tools/ci/scripts/install_openssl_formula_dependencies.ps1
  tools/codegen/genwebsitejson.py
  tools/codegen/genwebsitemetadata.py
  tools/deployment/copyright.debian
  tools/deployment/make_windows_package.ps1
  tools/deployment/osqueryctl
  tools/windows_resources.rc.in
Labels: documentation, foundation, refactor

#6592 Set global output function for Thrift
  osquery/extensions/impl_thrift.cpp
Labels: Windows, user experience

#6586 Remove ExecStartPre from systemd service unit -- do not create empty config file
  tools/deployment/osqueryd.service
Labels: Linux, packaging

#6608 bug: Improve chassis_types and security_breach columns within chassis_info
  osquery/core/windows/wmi.cpp
  osquery/core/windows/wmi.h
  osquery/tables/system/windows/chassis_info.cpp
  specs/windows/chassis_info.table
  tests/integration/tables/chassis_info.cpp
Labels: Windows, virtual tables

#6563 Add non-evented table for querying Windows Events Log
  osquery/events/windows/windowseventlogparser.cpp
  osquery/events/windows/windowseventlogparser.h
  osquery/tables/events/tests/windows/windows_events_tests.cpp
  osquery/tables/system/CMakeLists.txt
  osquery/tables/system/tests/CMakeLists.txt
  osquery/tables/system/tests/windows/windows_eventlog_tests.cpp
  osquery/tables/system/windows/windows_eventlog.cpp
  osquery/tables/system/windows/windows_eventlog.h
  specs/CMakeLists.txt
  specs/windows/windows_eventlog.table
  tests/integration/tables/CMakeLists.txt
  tests/integration/tables/windows_eventlog.cpp
Labels: Windows, virtual tables

#6604 bug: Apply watcher delay each time the worker is started
  osquery/core/tests/watcher_tests.cpp
  osquery/core/watcher.cpp
  osquery/core/watcher.h
Labels: bug

#6605 shell: Return early if relative flags are used
  osquery/core/shutdown.cpp
  osquery/core/shutdown.h
  osquery/main/main.cpp
Labels: shell, user experience

#6606 bug: Fix buildup of RocksDB SST files
  libraries/cmake/source/rocksdb/CMakeLists.txt
  plugins/database/rocksdb.cpp
  plugins/database/rocksdb.h
  plugins/database/tests/utils.cpp
Labels: bug, database, libraries

#6611 Restore PIE support being dropped on Linux
  cmake/flags.cmake
  cmake/toolchain.cmake
  osquery/main/harnesses/CMakeLists.txt
Labels: build, cmake, hardening

#6617 docs: Replace slackin with Slack shared invite
  CONTRIBUTING.md
  README.md
  SECURITY.md
  SUPPORT.md
  docs/wiki/index.md
  tools/deployment/make_windows_package.ps1
Labels: documentation

#6568 Add `sigrules` to pass YARA signature with query
  osquery/tables/yara/tests/yara_tests.cpp
  osquery/tables/yara/yara.cpp
  osquery/tables/yara/yara_utils.cpp
  osquery/tables/yara/yara_utils.h
  specs/yara/yara.table
Labels: feature

#4982 [WIP] apparmor_events table in osquery
  osquery/events/CMakeLists.txt
  osquery/events/linux/apparmor_events.h
  osquery/events/linux/auditdnetlink.cpp
  osquery/events/linux/auditdnetlink.h
  osquery/events/linux/auditeventpublisher.cpp
  osquery/events/linux/auditeventpublisher.h
  osquery/tables/events/CMakeLists.txt
  osquery/tables/events/linux/apparmor_events.cpp
  osquery/tables/events/linux/apparmor_events.h
  specs/CMakeLists.txt
  specs/linux/apparmor_events.table
Labels: Linux, cla signed, events, virtual tables

#6614 database: Change reset interval from 5m to 1hr
  osquery/dispatcher/scheduler.cpp
Labels: database, performance

#6619 refactor: Change the include path for osquery/core/plugins
  osquery/config/config.h
  osquery/core/plugins/CMakeLists.txt
  osquery/core/plugins/logger.h
  osquery/core/plugins/sql.h
  osquery/core/tables.h
  osquery/database/database.h
  osquery/distributed/distributed.cpp
  osquery/distributed/distributed.h
  osquery/experimental/events_stream/events_stream_registry.h
  osquery/extensions/extensions.h
  osquery/logger/data_logger.h
  osquery/logger/logger.cpp
  osquery/logger/tests/logger.cpp
  osquery/numeric_monitoring/plugin_interface.cpp
  osquery/numeric_monitoring/plugin_interface.h
  osquery/registry/registry.h
  osquery/registry/registry_interface.h
  osquery/remote/enroll/enroll.h
  osquery/sql/sql.cpp
  osquery/sql/sqlite_util.cpp
  plugins/logger/aws_firehose.h
  plugins/logger/aws_kinesis.h
  plugins/logger/aws_log_forwarder.h
  plugins/logger/buffered.h
  plugins/logger/filesystem_logger.h
  plugins/logger/kafka_producer.h
  plugins/logger/stdout.h
  plugins/logger/syslog_logger.h
  plugins/logger/tls_logger.h
  plugins/logger/windows_event_log.h
Labels: refactor
