Repository osquery/osquery, pull requests merged in 2021-01, with the labels that each got.

#6876 Fix config validation oom with duplicated keys
  osquery/config/config.cpp
  osquery/config/tests/config_tests.cpp
Labels: bug, configuration

#6878 Remove unused ev2 code
  osquery/CMakeLists.txt
  osquery/ev2/CMakeLists.txt
  osquery/ev2/buffered_subscription.h
  osquery/ev2/manager.cpp
  osquery/ev2/manager.h
  osquery/ev2/publisher.cpp
  osquery/ev2/publisher.h
  osquery/ev2/simple_publisher.h
  osquery/ev2/subscription.cpp
  osquery/ev2/subscription.h
  osquery/ev2/tests/buffered_subscription.cpp
  osquery/ev2/tests/manager.cpp
  osquery/ev2/tests/simple_publisher.cpp
  osquery/ev2/tests/utils.cpp
  osquery/ev2/tests/utils.h
Labels: dead code, events

#6879 Remove unused/experimental ebpf code
  osquery/experimental/CMakeLists.txt
  osquery/experimental/tracing/CMakeLists.txt
  osquery/experimental/tracing/linux/CMakeLists.txt
  osquery/experimental/tracing/linux/ebpf_tracepoint.cpp
  osquery/experimental/tracing/linux/ebpf_tracepoint.h
  osquery/experimental/tracing/linux/probes.cpp
  osquery/experimental/tracing/linux/probes.h
  osquery/experimental/tracing/linux/syscall_event.cpp
  osquery/experimental/tracing/linux/syscall_event.h
  osquery/experimental/tracing/linux/syscalls_programs.cpp
  osquery/experimental/tracing/linux/syscalls_programs.h
  osquery/experimental/tracing/linux/tests/CMakeLists.txt
  osquery/experimental/tracing/linux/tests/empty.cpp
  osquery/experimental/tracing/linux/tests/syscall_event.cpp
  osquery/experimental/tracing/syscalls_tracing.cpp
  osquery/experimental/tracing/syscalls_tracing.h
  osquery/experimental/tracing/syscalls_tracing_impl.cpp
  osquery/experimental/tracing/syscalls_tracing_impl.h
  osquery/main/CMakeLists.txt
  osquery/main/harnesses/CMakeLists.txt
  osquery/main/main.cpp
  osquery/utils/system/linux/CMakeLists.txt
  osquery/utils/system/linux/ebpf/CMakeLists.txt
  osquery/utils/system/linux/ebpf/ebpf.cpp
  osquery/utils/system/linux/ebpf/ebpf.h
  osquery/utils/system/linux/ebpf/map.cpp
  osquery/utils/system/linux/ebpf/map.h
  osquery/utils/system/linux/ebpf/perf_output.h
  osquery/utils/system/linux/ebpf/perf_output_impl.h
  osquery/utils/system/linux/ebpf/program.cpp
  osquery/utils/system/linux/ebpf/program.h
  osquery/utils/system/linux/ebpf/tests/CMakeLists.txt
  osquery/utils/system/linux/ebpf/tests/ebpf.cpp
  osquery/utils/system/linux/ebpf/tests/empty.cpp
  osquery/utils/system/linux/ebpf/tests/map.cpp
  osquery/utils/system/linux/ebpf/tests/perf_output.cpp
  osquery/utils/system/linux/ebpf/tests/program.cpp
  osquery/utils/system/linux/perf_event/CMakeLists.txt
  osquery/utils/system/linux/perf_event/perf_event.cpp
  osquery/utils/system/linux/perf_event/perf_event.h
  osquery/utils/system/linux/tracing/CMakeLists.txt
  osquery/utils/system/linux/tracing/native_event.cpp
  osquery/utils/system/linux/tracing/native_event.h
  osquery/utils/system/linux/tracing/tests/CMakeLists.txt
  osquery/utils/system/linux/tracing/tests/empty.cpp
  osquery/utils/system/linux/tracing/tests/native_event.cpp
  osquery/utils/system/linux/tracing/types.h
Labels: bpf, dead code

#6877 Update README to include release process comment
  CONTRIBUTING.md
  README.md
Labels: documentation

#6880 Fix heap-use-after-free in deregisterEventSubscriber
  osquery/events/eventfactory.cpp
Labels: bug, events

#6881 Fix UB and dangerous casting in the pubsub framework
  osquery/events/eventfactory.cpp
  osquery/events/eventfactory.h
  osquery/events/eventpublisherplugin.h
  osquery/events/eventsubscriber.h
  osquery/events/eventsubscriberplugin.cpp
  osquery/events/eventsubscriberplugin.h
  osquery/events/types.h
Labels: bug, events

#6882 Fix broken url in docs
  docs/wiki/development/creating-tables.md
Labels: documentation

#6888 Add docs for tls enroll max attempts
  docs/wiki/installation/cli-flags.md
Labels: documentation, remote

#6892 Fix a leak in libdpkg when querying the deb_packages table
  libraries/cmake/source/libdpkg/CMakeLists.txt
  libraries/cmake/source/libdpkg/patches/src/fix-memory-leak.patch
  libraries/cmake/source/modules/Findlibdpkg.cmake
Labels: libraries, memory leak

#6884 docker_image_history table
  osquery/tables/applications/posix/docker.cpp
  specs/CMakeLists.txt
  specs/posix/docker_image_history.table
  tests/integration/tables/CMakeLists.txt
  tests/integration/tables/docker_image_history.cpp
Labels: docker, virtual tables

#6893 Fix loading of YARA rules on Windows
  osquery/tables/yara/yara_utils.cpp
Labels: Windows, bug

#6863 System extension table in macOS
  osquery/tables/system/CMakeLists.txt
  osquery/tables/system/darwin/system_extensions.mm
  osquery/tables/system/tests/CMakeLists.txt
  osquery/tables/system/tests/darwin/system_extensions_test.cpp
  specs/CMakeLists.txt
  specs/darwin/system_extensions.table
  tests/integration/tables/CMakeLists.txt
  tests/integration/tables/system_extensions.cpp
  tools/tests/configs/db.plist
Labels: feature, macOS, macOS Big Sur, macOS Catalina, virtual tables

#6886 Reduce the compilation units from libarchive
  libraries/cmake/source/libarchive/CMakeLists.txt
Labels: build, libraries

#6875 Restrict access to Thrift server pipe on Windows
  osquery/extensions/impl_thrift.cpp
Labels: Windows, extensions, ready for review, security

#6898 Disable incremental linking to reduce build size on Windows
  cmake/flags.cmake
Labels: Windows, build, cmake

#6899 Spellcheck and Markdown nits
  README.md
  docs/wiki/deployment/extensions.md
  docs/wiki/deployment/log-aggregation.md
  docs/wiki/deployment/performance-safety.md
  docs/wiki/deployment/process-auditing.md
  docs/wiki/deployment/syslog.md
  docs/wiki/development/creating-tables.md
  docs/wiki/development/osquery-sdk.md
  docs/wiki/development/pubsub-framework.md
  docs/wiki/development/unit-tests.md
  docs/wiki/installation/cli-flags.md
  docs/wiki/installation/install-linux.md
  docs/wiki/introduction/using-osqueryi.md
Labels: documentation

#6885 CI: Add support for GitHub Actions
  .github/workflows/build.yml
  README.md
  osquery/empty.cpp
  osquery/filesystem/tests/filesystem.cpp
  osquery/tables/system/darwin/ibridge.cpp
  osquery/utils/tests/rot13.cpp
  tests/integration/tables/ibridge.cpp
  tools/ci/scripts/check_copyright_headers.py
Labels: CI/CD, Linux, Windows, macOS

#6900 Remove unused tests for Rocksdb and Inmemory db plugins
  osquery/core/plugins/tests/in_memory_database_tests.cpp
  osquery/core/plugins/tests/rocksdb_database_tests.cpp
Labels: dead code

#6894 Fix additional relative path check in Yara for Windows
  osquery/tables/yara/yara.cpp
Labels: Windows, bug

#6909 CMake: Add -pthread compile option on posix platforms
  cmake/flags.cmake
Labels: build, cmake

#6903 Change libdpkg submodule url to our own github mirror
  .gitmodules
Labels: libraries, oss-fuzz

#6908 Fix Github Actions status badge in the README
  README.md
Labels: CI/CD, documentation

#6910 Disable deprecated TLS versions 1.0, 1.1
  osquery/remote/transports/tls.cpp
Labels: networking, ready for review, security

#6896 [macOS][CI] Update XCode to 12.3 and Update min macOS version to 10.12
  azure-pipelines.yml
  docs/wiki/development/building.md
  docs/wiki/installation/install-macos.md
Labels: CI/CD, macOS

#6913 GitHub Actions: Use Xcode 12.3, SDK 10.12
  .github/workflows/build.yml
Labels: CI/CD, macOS

#6918 Remove unused empty test file
  osquery/tables/yara/tests/yara_tests_win_empty.cpp
Labels: dead code

#6920 GitHub Actions: Fix .deb artifacts, add scheduled builds
  .github/workflows/build.yml
Labels: CI/CD, packaging

#6917 Rename yara str functions to avoid symbol collisions
  libraries/cmake/source/modules/Findyara.cmake
  libraries/cmake/source/yara/CMakeLists.txt
  libraries/cmake/source/yara/patches/src/yara-strutils.patch
Labels: build, cmake, libraries

#6922 Update documentation about denylist schedule key
  docs/wiki/deployment/configuration.md
Labels: documentation, performance

#6919 Add unit tests for RPM DB querying
  osquery/tables/system/CMakeLists.txt
  osquery/tables/system/tests/CMakeLists.txt
  osquery/tables/system/tests/linux/rpm_packages_tests.cpp
  tools/tests/configs/rpm/rpm-bdb/.rpm.lock
  tools/tests/configs/rpm/rpm-bdb/Basenames
  tools/tests/configs/rpm/rpm-bdb/Conflictname
  tools/tests/configs/rpm/rpm-bdb/Dirnames
  tools/tests/configs/rpm/rpm-bdb/Filedigests
  tools/tests/configs/rpm/rpm-bdb/Group
  tools/tests/configs/rpm/rpm-bdb/Installtid
  tools/tests/configs/rpm/rpm-bdb/Name
  tools/tests/configs/rpm/rpm-bdb/Obsoletename
  tools/tests/configs/rpm/rpm-bdb/Packages
  tools/tests/configs/rpm/rpm-bdb/Providename
  tools/tests/configs/rpm/rpm-bdb/Provideversion
  tools/tests/configs/rpm/rpm-bdb/Pubkeys
  tools/tests/configs/rpm/rpm-bdb/Requirename
  tools/tests/configs/rpm/rpm-bdb/Requireversion
  tools/tests/configs/rpm/rpm-bdb/Sha1header
  tools/tests/configs/rpm/rpm-bdb/Sigmd5
  tools/tests/configs/rpm/rpm-bdb/Triggername
Labels: Linux, test

#6932 Fix SystemControlsTest adding sunrpc as an expected subsystem
  tests/integration/tables/system_controls.cpp
Labels: bug, test
