Repository osquery/osquery, pull requests merged in 2021-11, with the labels that each got.

#7355 Windows: Detect when an extension has not started
  osquery/process/windows/process.cpp
Labels: bug, extensions, Windows

#7349 `curl` table now returns peer certificates even if the TLS handshake does not complete
  osquery/tables/networking/curl_certificate.cpp
Labels: bug, virtual tables, ready for review

#7367 Respect `read_max` flag when hashing using ssdeep
  osquery/tables/system/hash.cpp
Labels: bug, virtual tables, performance

#7348 Allow custom cpu limit duration for the watchdog
  docs/wiki/installation/cli-flags.md
  osquery/core/watcher.cpp
Labels: feature, ready for review, performance

#7376 Fix typo in SQL docs
  docs/wiki/introduction/sql.md
Labels: documentation

#7388 Restore query packs in Windows packaging
  .github/workflows/build_aarch64.yml
  .github/workflows/build_x86.yml
  cmake/install_directives.cmake
Labels: Windows, packaging

#7372 Allow tests and SDK to reset dispatcher state
  osquery/dispatcher/dispatcher.h
Labels: user experience, test

#7373 Allow tests to reset the restarting state
  osquery/core/shutdown.cpp
  osquery/core/shutdown.h
Labels: user experience

#7396 Update github issue template to link to slack
  .github/ISSUE_TEMPLATE/Question.md
Labels: documentation
