Repository osquery/osquery, pull requests merged in 2021-12, with the labels that each got.

#7401 Fix crash when windows_security_products errors out
  osquery/tables/system/windows/windows_security_products.cpp
Labels: bug, virtual tables, Windows

#7404 CI: Update packaging commit to fix Linux symlinks
  .github/workflows/build_aarch64.yml
  .github/workflows/build_x86.yml
Labels: packaging, CI/CD

#7406 CHANGELOG 5.1.0
  CHANGELOG.md
Labels: documentation

#7412 fix: remove typo
  docs/wiki/development/building.md
Labels: documentation

#7411 Hide the deprecate `antispyware` column in `windows_security_center`
  specs/windows/windows_security_center.table
Labels: virtual tables, Windows

#7418 Prevent running discovery queries when fuzzing
  osquery/config/config.cpp
Labels: oss-fuzz

#7419 Fix how we disable tables in the fuzzer init method
  osquery/main/harnesses/fuzz_utils.cpp
Labels: oss-fuzz

#7425 Fix linking of thirdparty_sleuthkit
  libraries/cmake/source/sleuthkit/CMakeLists.txt
Labels: build, oss-fuzz

#7276 Set local_time column on time table to hidden
  docs/wiki/installation/cli-flags.md
  osquery/core/system.cpp
  osquery/tables/utility/time.cpp
  specs/utility/time.table
  tests/integration/tables/time.cpp
Labels: virtual tables
