Repository osquery/osquery, pull requests merged in 2021-09, with the labels that each got.

#7282 Linux: Support AF_PACKET sockets.
  osquery/filesystem/CMakeLists.txt
  osquery/filesystem/linux/proc.cpp
  osquery/filesystem/linux/proc.h
  osquery/filesystem/tests/linux/proc_tests.cpp
  osquery/tables/networking/linux/process_open_sockets.cpp
Labels: virtual tables, Linux, networking

#7295 Prevent osquery from killing itself when the --force flag is used
  osquery/core/system.cpp
Labels: bug, daemon

#7190 Add TimeoutStopSec to systemd service files
  tools/deployment/linux_packaging/deb/osqueryd.service
  tools/deployment/linux_packaging/rpm/osqueryd.service
Labels: Linux, deployment

#7294 Build librpm with ndb support
  libraries/cmake/source/librpm/CMakeLists.txt
  libraries/cmake/source/librpm/README.md
  libraries/cmake/source/librpm/config/config.h
  osquery/tables/system/tests/linux/rpm_packages_tests.cpp
  tools/tests/configs/rpm/rpm-ndb/.rpm.lock
  tools/tests/configs/rpm/rpm-ndb/Index.db
  tools/tests/configs/rpm/rpm-ndb/Packages.db
Labels: build, packaging

#7303 docs: update macOS ESF documentation
  docs/wiki/deployment/process-auditing.md
  docs/wiki/installation/cli-flags.md
Labels: macOS, documentation

#7284 Changelog 5.0.0
  CHANGELOG.md
Labels: documentation, release

#7311 Update installation guide to use newer macOS paths
  docs/wiki/installation/install-macos.md
Labels: documentation

#7317 [AWS] Support custom endpoints for Kinesis and Firehose.
  docs/wiki/deployment/aws-logging.md
  osquery/utils/aws/aws_util.cpp
  osquery/utils/aws/aws_util.h
  osquery/utils/aws/tests/aws_util_tests.cpp
  plugins/logger/aws_firehose.cpp
  plugins/logger/aws_firehose.h
  plugins/logger/aws_kinesis.cpp
  plugins/logger/aws_kinesis.h
  plugins/logger/aws_log_forwarder.h
  plugins/logger/tests/aws_kinesis_logger_tests.cpp
Labels: ready for review, logging, AWS

#7318 Reduce excessive log messages from authorized_keys table implementation
  osquery/tables/system/posix/authorized_keys.cpp
Labels: ready for review, user experience, logging, easy

#7315 Customizable installation logic
  CMakeLists.txt
  cmake/install_directives.cmake
  cmake/options.cmake
Labels: feature, build, cmake
