Repository osquery/osquery, pull requests merged in 2022-05, with the labels that each got.

#7156 Add original filename column to file table on Windows
  osquery/filesystem/fileops.h
  osquery/filesystem/windows/fileops.cpp
  osquery/tables/utility/file.cpp
  specs/utility/file.table
  tests/integration/tables/file.cpp
Labels: virtual tables, Windows

#7563 Add CIDR function as custom SQLite function
  docs/wiki/introduction/sql.md
  osquery/sql/CMakeLists.txt
  osquery/sql/sqlite_network.cpp
  osquery/sql/sqlite_util.cpp
  osquery/sql/sqlite_util.h
  osquery/sql/tests/CMakeLists.txt
  osquery/sql/tests/sqlite_network_tests.cpp
Labels: feature, SQL

#7584 Remove the test_daemon_sighup test
  tools/tests/test_osqueryd.py
Labels: bug, flaky test

#7583 Warn about setting CLI_FLAGs in the config
  osquery/core/flags.cpp
  osquery/core/flags.h
  osquery/sql/sqlite_util.cpp
  plugins/config/parsers/options.cpp
Labels: configuration, deprecation

#7446 bpf: Improve socket event handling
  osquery/events/linux/bpf/systemstatetracker.cpp
  osquery/events/tests/linux/bpf/systemstatetracker.cpp
Labels: bug, Linux, ready for review, bpf

#7596 Correct the section where the users and groups service flags are described
  docs/wiki/installation/cli-flags.md
Labels: documentation, Windows

#7595 Remove CLI flags settings from osquery.example.conf
  osquery/logger/logger.cpp
  tools/deployment/osquery.example.conf
Labels: configuration, deprecation

#7608 Fix a UUID typo in the `disk_encryption` table
  osquery/tables/system/darwin/disk_encryption.mm
Labels: bug, macOS

#7607 Update the "new release" issue template
  .github/ISSUE_TEMPLATE/Blueprint.md
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Free_Form.md
  .github/ISSUE_TEMPLATE/New_Release.md
  .github/ISSUE_TEMPLATE/Question.md
Labels: ready for review, documentation, development

#7575 CHANGELOG 5.3.0
  CHANGELOG.md
Labels: documentation, release
