Repository osquery/osquery, pull requests merged in 2022-01, with the labels that each got.

#7439 Fix a crash when Yara uses its own strutils functions
  libraries/cmake/source/yara/patches/strutils.cpp
  osquery/tables/yara/tests/yara_tests.cpp
Labels: bug, libraries

#7443 Fix typos in documentation
  CHANGELOG.md
  docs/wiki/deployment/configuration.md
  osquery/experimental/README.md
Labels: documentation

#7442 Update the ATC table `path` column check to be case insensitive
  osquery/sql/virtual_sqlite_table.cpp
  plugins/config/parsers/auto_constructed_tables.cpp
Labels: bug

#7437 [docs] remove utc flag from example config file
  tools/deployment/osquery.example.conf
Labels: documentation

#7403 New Table: Windows Firewall Rules
  osquery/tables/networking/CMakeLists.txt
  osquery/tables/networking/tests/CMakeLists.txt
  osquery/tables/networking/tests/windows/windows_firewall_rules_tests.cpp
  osquery/tables/networking/windows/windows_firewall_rules.cpp
  osquery/tables/networking/windows/windows_firewall_rules.h
  specs/CMakeLists.txt
  specs/windows/windows_firewall_rules.table
  tests/integration/tables/CMakeLists.txt
  tests/integration/tables/windows_firewall_rules.cpp
Labels: feature, virtual tables, Windows

#7452 Add osquery version to macOS app bundle Info.plist
  cmake/utilities.cmake
  tools/deployment/macos_packaging/Info.plist
  tools/deployment/macos_packaging/Info.plist.in
Labels: build, macOS, ready for review, user experience, packaging

#7451 Removing unnecessary macOS version check
  osquery/tables/system/darwin/signature.mm
Labels: macOS, ready for review
