Repository osquery/osquery, pull requests merged in 2024-02, with the labels that each got.

#8253 Update description for amperage in battery table.
  specs/darwin/battery.table
Labels: macOS, ready for review, documentation

#8262 cve: Update openssl to 3.2.1
  libraries/cmake/formula/openssl/CMakeLists.txt
  libraries/third_party_libraries_manifest.json
Labels: libraries, cve

#8251 Refactor macOS system profile report retrieval
  osquery/tables/applications/CMakeLists.txt
  osquery/tables/system/CMakeLists.txt
  osquery/tables/system/darwin/connected_displays.mm
  osquery/tables/system/darwin/secureboot.mm
  osquery/tables/system/tests/CMakeLists.txt
  osquery/utils/CMakeLists.txt
  osquery/utils/darwin/system_profiler.h
  osquery/utils/darwin/system_profiler.mm
  osquery/utils/tests/darwin/system_profiler.mm
Labels: macOS, ready for review, refactor

#7461 Fix packs to check for platform before including queries
  tools/tests/utils.py
Labels: bug, macOS, ready for review, packs
