Repository osquery/osquery, pull requests merged in 2024-07, with the labels that each got.

#8307 Add support for metalink and store repo config file name in yum_sources table
  osquery/tables/system/linux/yum_sources.cpp
  osquery/tables/system/tests/linux/yum_sources_tests.cpp
  specs/linux/yum_sources.table
Labels: virtual tables, Linux

#8359 CI: Update macos builder to 14 and tester to 12
  .github/workflows/hosted_runners.yml
  osquery/dispatcher/tests/scheduler.cpp
  osquery/tables/system/tests/darwin/firewall_tests.cpp
Labels: macOS, CI/CD

#8365 Docs: improve explanation of required columns
  docs/wiki/introduction/sql.md
Labels: documentation, website

#8364 Fill in missing column descriptions to spec for `device_partitions`
  specs/sleuthkit/device_partitions.table
Labels: virtual tables, documentation

#8363 Update `processes` table spec and docs, to remove outdated column alias
  docs/wiki/introduction/sql.md
  specs/posix/docker_container_processes.table
  specs/processes.table
Labels: virtual tables, documentation

#8361 Make fallthrough explicit in sqlite_encoding.cpp
  osquery/sql/sqlite_encoding.cpp
Labels: documentation

#8324 add pending state to ATC tables to avoid duplicate sql attaches
  osquery/core/tables.h
  osquery/sql/virtual_table.cpp
  plugins/config/parsers/auto_constructed_tables.cpp
  plugins/config/parsers/auto_constructed_tables.h
Labels: SQL, core

#8303 Fix util-linux submodule url
  .gitmodules
Labels: build, CI/CD

#8345 Add `sha256` hash to `apparmor_profiles` table
  osquery/tables/system/linux/apparmor_profiles.cpp
  specs/linux/apparmor_profiles.table
Labels: virtual tables, Linux

#8369 ci: Update Linux Docker image to Ubuntu 20.04
  .github/workflows/hosted_runners.yml
  .github/workflows/self_hosted_runners.yml
  tools/ci/Makefile
  tools/ci/osquery-ubuntu20.04-toolchain.dockerfile
Labels: CI/CD

#8383 build: Correct xz submodule url and openssl download url
  .gitmodules
  libraries/cmake/formula/openssl/CMakeLists.txt
Labels: bug, build, CI/CD

#8371 Update description for alf_explicit_auths.
  specs/darwin/alf_explicit_auths.table
Labels: documentation
