Repository osquery/osquery, pull requests merged in 2024-09, with the labels that each got.

#8400 Add missing includes causing compilation error with Clang 18.1.8
  osquery/core/core.h
  osquery/core/shutdown.cpp
  osquery/core/sql/query_data.cpp
  osquery/core/sql/scheduled_query.h
  osquery/core/tests/process_tests.cpp
  osquery/core/watcher.cpp
  osquery/logger/logger.cpp
  osquery/remote/uri.h
  osquery/tables/system/posix/openssl_utils.cpp
  osquery/tables/system/tests/system_tables_tests.cpp
  osquery/utils/pidfile/tests/pidfile.cpp
  osquery/utils/system/posix/time.cpp
  osquery/utils/system/time.h
  osquery/utils/tests/scope_guard.cpp
  tests/integration/tables/process_open_files.cpp
Labels: build, Linux

#8416 ci: Update the upload-artifact action to v4.4.0
  .github/workflows/hosted_runners.yml
Labels: bug, CI/CD

#8412 build: Cleanups and fixes for a newer clang toolchain
  cmake/flags.cmake
  cmake/toolchain.cmake
  osquery/tables/system/linux/rpm_packages.cpp
Labels: build, Linux

#8370 Add `CHANGELOG.md` entry for 5.13.1
  CHANGELOG.md
Labels: documentation, release

#8409 Boost 1.86 compatibility
  osquery/filesystem/linux/proc.h
  osquery/filesystem/tests/filesystem.cpp
  osquery/tables/applications/chrome/tests/utils.cpp
  osquery/tables/applications/posix/docker.cpp
  osquery/tables/events/linux/process_file_events.cpp
  osquery/tables/events/windows/powershell_events.cpp
  osquery/tables/sleuthkit/sleuthkit.cpp
  osquery/utils/aws/aws_util.cpp
  tests/integration/tables/mdfind.cpp
Labels: build

#8394 Fix for `windows_crashes` missing information on user mode memory dumps
  osquery/tables/system/windows/windows_crashes.cpp
Labels: virtual tables, Windows

#8390 Rename `hvci_status` to `deviceguard_status` to better reflect the data collected.
  osquery/tables/system/CMakeLists.txt
  osquery/tables/system/windows/deviceguard_status.cpp
  specs/CMakeLists.txt
  specs/windows/deviceguard_status.table
  tests/integration/tables/CMakeLists.txt
  tests/integration/tables/deviceguard_status.cpp
Labels: bug, virtual tables, Windows
